In [2]:
import pandas as pd
import sqlite3

In [ ]:
conn = sqlite3.connect("ProductDB/Product.db")

df_Products = pd.read_sql_query( 'SELECT * FROM Products', conn )
df_Orders = pd.read_sql_query( 'SELECT * FROM Orders', conn )

### INNER JOIN - Display Only Common Values - Intersection

In [5]:
df_1_inner = pd.read_sql_query( 'SELECT productName, productType, productPrice, orderQuantity, productPrice * orderQuantity AS totalAmount FROM Products INNER JOIN Orders ON Products.productID = Orders.productID', conn )
print( 'Inner Join Shape = ', df_1_inner.shape )
df_1_inner

Inner Join Shape =  (3, 5)

    productName productType  productPrice  orderQuantity  totalAmount
0  Apple iPhone  SmartPhone        1234.0              5       6170.0
1    HP Spectre      Laptop        2222.0              2       4444.0
2  Garmin Watch  Smartwatch         555.0             10       5550.0

### RIGHT JOIN - All Values from Right Table and only Matching Values from the Left Table

In [6]:
df_1_right = pd.read_sql_query( 'SELECT productName, productType, productPrice, orderQuantity, productPrice * orderQuantity AS totalAmount FROM Products RIGHT JOIN Orders ON Products.productID = Orders.productID', conn )
print( 'Right Join Shape = ', df_1_right.shape )
df_1_right.tail()

Right Join Shape =  (3, 5)

    productName productType  productPrice  orderQuantity  totalAmount
0  Apple iPhone  SmartPhone        1234.0              5       6170.0
1    HP Spectre      Laptop        2222.0              2       4444.0
2  Garmin Watch  Smartwatch         555.0             10       5550.0

### LEFT JOIN - All Values from Left Table and only Matching Values from the Right Table

In [7]:
df_1_left = pd.read_sql_query( 'SELECT productName, productType, productPrice, orderQuantity, productPrice * orderQuantity AS totalAmount FROM Products LEFT JOIN Orders ON Products.productID = Orders.productID', conn )
print( 'Left Join Shape = ', df_1_left.shape )
df_1_left.tail(10)

Left Join Shape =  (4, 5)

    productName     productType  productPrice  orderQuantity  totalAmount
0  Apple iPhone      SmartPhone        1234.0            5.0       6170.0
1    HP Spectre          Laptop        2222.0            2.0       4444.0
2  Garmin Watch      Smartwatch         555.0           10.0       5550.0
3     Nespresso  Coffee Machine         333.0            NaN          NaN

### Cross Join – Here we get the cartesian product
- **Cartesian Product = number of rows of table1 * number of rows of table2**

In [8]:
df_1_cross = pd.read_sql_query( 'SELECT * FROM Products CROSS JOIN Orders', conn )
print( 'Products Shape = ', df_Products.shape )
print( 'Orders Shape = ', df_Orders.shape )
print( 'Cross Join Shape = ', df_1_cross.shape )
df_1_cross

Products Shape =  (4, 4)
Orders Shape =  (3, 3)
Cross Join Shape =  (12, 7)

,productID,productName,productType,productPrice,orderID,orderQuantity,productID
0,1,Apple iPhone,SmartPhone,1234.0,1,5,1
1,1,Apple iPhone,SmartPhone,1234.0,2,2,2
2,1,Apple iPhone,SmartPhone,1234.0,3,10,3
3,2,HP Spectre,Laptop,2222.0,1,5,1
4,2,HP Spectre,Laptop,2222.0,2,2,2
5,2,HP Spectre,Laptop,2222.0,3,10,3
6,3,Garmin Watch,Smartwatch,555.0,1,5,1
7,3,Garmin Watch,Smartwatch,555.0,2,2,2
8,3,Garmin Watch,Smartwatch,555.0,3,10,3
9,4,Nespresso,Coffee Machine,333.0,1,5,1
10,4,Nespresso,Coffee Machine,333.0,2,2,2
11,4,Nespresso,Coffee Machine,333.0,3,10,3

***

### Merge DataFrames using Left, Right Outer and Inner : .merge()
- **Similar to SQL JOINS**
- Merge DataFrame1 and DataFrame2 and Pass as an Argument with DataFrame3

#### Inner Join

In [9]:
df_2_inner = pd.merge( df_Orders, df_Products, on='productID', how='inner')
print( 'Inner Join Shape = ', df_2_inner.shape )
df_2_inner.tail()

Inner Join Shape =  (3, 6)

   orderID  orderQuantity  productID   productName productType  productPrice
0        1              5          1  Apple iPhone  SmartPhone        1234.0
1        2              2          2    HP Spectre      Laptop        2222.0
2        3             10          3  Garmin Watch  Smartwatch         555.0

### Outer Join:
- Return Matched and Unmatched Values from either or both the Tables

In [10]:
df_2_outer = pd.merge( df_Orders, df_Products, on='productID', how='outer')
print( 'Outer Join Shape = ', df_2_outer.shape )
df_2_outer

Outer Join Shape =  (4, 6)

,orderID,orderQuantity,productID,productName,productType,productPrice
0,1.0,5.0,1,Apple iPhone,SmartPhone,1234.0
1,2.0,2.0,2,HP Spectre,Laptop,2222.0
2,3.0,10.0,3,Garmin Watch,Smartwatch,555.0
3,NaN,NaN,4,Nespresso,Coffee Machine,333.0

#### Left Join

In [11]:
df_2_left = pd.merge( df_Orders, df_Products, on='productID', how='left')
print( 'Left Join Shape = ', df_2_left.shape )
df_2_left

Left Join Shape =  (3, 6)

   orderID  orderQuantity  productID   productName productType  productPrice
0        1              5          1  Apple iPhone  SmartPhone        1234.0
1        2              2          2    HP Spectre      Laptop        2222.0
2        3             10          3  Garmin Watch  Smartwatch         555.0

#### Right Join

In [12]:
df_2_right = pd.merge( df_Orders, df_Products, on='productID', how='right')
print( 'Right Join Shape = ', df_2_right.shape )
df_2_right.tail()

Right Join Shape =  (4, 6)

,orderID,orderQuantity,productID,productName,productType,productPrice
0,1.0,5.0,1,Apple iPhone,SmartPhone,1234.0
1,2.0,2.0,2,HP Spectre,Laptop,2222.0
2,3.0,10.0,3,Garmin Watch,Smartwatch,555.0
3,NaN,NaN,4,Nespresso,Coffee Machine,333.0

***

### join() is used to combine DataFrames based on their indices.
- **join() merges two or more tables horizontally (side by side)**
- **Both DataFrames must have the same or compatible indices.**

#### Let's Set the Index to Common Column ProductID for both the dataFrames

In [18]:
df_Products = df_Products.set_index('productID')
df_Products

            productName     productType  productPrice
productID
1          Apple iPhone      SmartPhone        1234.0
2            HP Spectre          Laptop        2222.0
3          Garmin Watch      Smartwatch         555.0
4             Nespresso  Coffee Machine         333.0

In [20]:
df_Orders = df_Orders.set_index('productID')
df_Orders

           orderID  orderQuantity
productID
1                1              5
2                2              2
3                3             10

In [21]:
df_join = df_Products.join( df_Orders )
df_join

            productName     productType  productPrice  orderID  orderQuantity
productID
1          Apple iPhone      SmartPhone        1234.0      1.0            5.0
2            HP Spectre          Laptop        2222.0      2.0            2.0
3          Garmin Watch      Smartwatch         555.0      3.0           10.0
4             Nespresso  Coffee Machine         333.0      NaN            NaN

***