In [1]:
pip install -r requirements.txt

Requirement already satisfied: numpy in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: pandas in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 2)) (2.3.3)
Requirement already satisfied: matplotlib in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 3)) (3.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\swares\exploded\python_3_12\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\swares\exploded\python_3_12\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\swares\exploded\python_3_12\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (24.2)
Requirement already satisfied: pillow>=8 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 3)) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\swares\exploded\python_3_12\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

***

#### Create Data using ChatGPT - create sample data frame of transactions at a coffee shop in CSV format with at least 25 rows, add a few missing values and NAN's and I want to be able to download the csv file

##### If unable to download create using Python

In [3]:
import pandas as pd
import numpy as np

data = [
    ["TX1001", "2025-09-08", "08:15:23", "Cappuccino", 1, 3.50, 3.50, "Credit Card"],
    ["TX1002", "2025-09-01", "08:22:11", "Latte", 2, 4.00, 8.00, "Cash"],
    ["TX1003", "2025-09-12", "08:35:46", "Espresso", 1, 2.75, 2.75, "Mobile Pay"],
    ["TX1004", "2025-09-03", "08:50:39", "Croissant", 1, 2.50, 2.50, "Credit Card"],
    ["TX1005", "2025-09-07", "09:00:02", "Americano", 1, 3.00, 3.00, None],
    ["TX1006", "2025-09-02", "09:05:55", "Mocha", None, 4.25, None, "Mobile Pay"],
    ["TX1007", "2025-09-15", "09:15:08", "Tea", 1, None, 2.25, "Credit Card"],
    ["TX1008", "2025-09-05", "09:30:42", "Latte", 1, 4.00, 4.00, "Mobile Pay"],
    ["TX1009", "2025-09-04", "09:45:14", "Bagel", 1, 2.75, 2.75, "Cash"],
    ["TX1010", "2025-09-10", "10:00:27", "Cappuccino", 2, 3.50, 7.00, "Credit Card"],
    ["TX1011", "2025-09-18", "10:15:50", "Espresso", 1, 2.75, np.nan, "Cash"],
    ["TX1012", "2025-09-21", "10:30:19", None, 1, 3.25, 3.25, "Credit Card"],
    ["TX1013", "2025-09-06", "10:45:34", "Mocha", 2, np.nan, None, "Mobile Pay"],
    ["TX1014", "2025-09-09", "11:00:06", "Bagel", 1, 2.75, 2.75, None],
    ["TX1015", "2025-09-14", "11:15:51", "Croissant", np.nan, 2.50, np.nan, "Credit Card"],
    ["TX1016", "2025-09-11", "11:30:45", "Latte", 1, 4.00, 4.00, "Credit Card"],
    ["TX1017", "2025-09-13", "11:45:29", "Cappuccino", 2, 3.50, 7.00, "Cash"],
    ["TX1018", "2025-09-16", "12:00:03", None, np.nan, np.nan, np.nan, np.nan],
    ["TX1019", "2025-09-17", "12:15:59", "Tea", 1, 2.25, 2.25, "Credit Card"],
    ["TX1020", "2025-09-19", "12:30:12", "Americano", 1, 3.00, 3.00, "Cash"],
    ["TX1021", "2025-09-20", "12:45:36", "Cappuccino", 1, 3.50, 3.50, "Credit Card"],
    ["TX1022", "2025-09-22", "13:00:28", "Latte", 2, 4.00, 8.00, "Mobile Pay"],
    ["TX1023", "2025-09-23", "13:15:17", "Muffin", 1, 2.75, 2.75, "Cash"],
    ["TX1024", "2025-09-24", "13:30:54", "Brownie", 1, 2.50, 2.50, None],
    ["TX1025", "2025-09-25", "13:45:31", "Espresso", None, 2.75, None, "Credit Card"],
    ["TX1026", "2025-09-26", "14:00:09", "Latte", 1, None, None, "Cash"]
]

columns = ["TransactionID", "Date", "Time", "Item", "Quantity", "PricePerItem", "TotalPrice", "PaymentMethod"]

df = pd.DataFrame(data, columns=columns)

# Save to CSV
df.to_csv("coffee_shop_transactions_with_missing_25_rows.csv", index=False)

In [4]:
df_2 = pd.read_csv( 'coffee_shop_transactions_with_missing_25_rows.csv' )
print( 'Top 10 : \n', df_2.head(10) )
print( '\n Bottom 10 : \n', df_2.tail(10) )
print( '\n Number of Rows,Cols : ', df_2.shape )

print( '\n Column Names: ', df_2.columns )

Top 10 :
   TransactionID        Date      Time        Item  Quantity  PricePerItem  \
0        TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50
1        TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
2        TX1003  2025-09-12  08:35:46    Espresso       1.0          2.75
3        TX1004  2025-09-03  08:50:39   Croissant       1.0          2.50
4        TX1005  2025-09-07  09:00:02   Americano       1.0          3.00
5        TX1006  2025-09-02  09:05:55       Mocha       NaN          4.25
6        TX1007  2025-09-15  09:15:08         Tea       1.0           NaN
7        TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
8        TX1009  2025-09-04  09:45:14       Bagel       1.0          2.75
9        TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50

   TotalPrice PaymentMethod
0        3.50   Credit Card
1        8.00          Cash
2        2.75    Mobile Pay
3        2.50   Credit Card
4        3.00           NaN
5         NaN    Mobile Pay
6        2.25   Credit Card
7        4.00    Mobile Pay
8        2.75          Cash
9        7.00   Credit Card

 Bottom 10 :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
16        TX1017  2025-09-13  11:45:29  Cappuccino       2.0          3.50
17        TX1018  2025-09-16  12:00:03         NaN       NaN           NaN
18        TX1019  2025-09-17  12:15:59         Tea       1.0          2.25
19        TX1020  2025-09-19  12:30:12   Americano       1.0          3.00
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
16        7.00          Cash
17         NaN           NaN
18        2.25   Credit Card
19        3.00          Cash
20        3.50   Credit Card
21        8.00    Mobile Pay
22        2.75          Cash
23        2.50           NaN
24         NaN   Credit Card
25         NaN          Cash

 Number of Rows,Cols :  (26, 8)

 Column Names:  Index(['TransactionID', 'Date', 'Time', 'Item', 'Quantity', 'PricePerItem',
       'TotalPrice', 'PaymentMethod'],
      dtype='object')

In [5]:
df_2

,TransactionID,Date,Time,Item,Quantity,PricePerItem,TotalPrice,PaymentMethod
0,TX1001,2025-09-08,08:15:23,Cappuccino,1.0,3.50,3.50,Credit Card
1,TX1002,2025-09-01,08:22:11,Latte,2.0,4.00,8.00,Cash
2,TX1003,2025-09-12,08:35:46,Espresso,1.0,2.75,2.75,Mobile Pay
3,TX1004,2025-09-03,08:50:39,Croissant,1.0,2.50,2.50,Credit Card
4,TX1005,2025-09-07,09:00:02,Americano,1.0,3.00,3.00,NaN
5,TX1006,2025-09-02,09:05:55,Mocha,NaN,4.25,NaN,Mobile Pay
6,TX1007,2025-09-15,09:15:08,Tea,1.0,NaN,2.25,Credit Card
7,TX1008,2025-09-05,09:30:42,Latte,1.0,4.00,4.00,Mobile Pay
8,TX1009,2025-09-04,09:45:14,Bagel,1.0,2.75,2.75,Cash
9,TX1010,2025-09-10,10:00:27,Cappuccino,2.0,3.50,7.00,Credit Card
10,TX1011,2025-09-18,10:15:50,Espresso,1.0,2.75,NaN,Cash
11,TX1012,2025-09-21,10:30:19,NaN,1.0,3.25,3.25,Credit Card
12,TX1013,2025-09-06,10:45:34,Mocha,2.0,NaN,NaN,Mobile Pay
13,TX1014,2025-09-09,11:00:06,Bagel,1.0,2.75,2.75,NaN
14,TX1015,2025-09-14,11:15:51,Croissant,NaN,2.50,NaN,Credit Card
15,TX1016,2025-09-11,11:30:45,Latte,1.0,4.00,4.00,Credit Card
16,TX1017,2025-09-13,11:45:29,Cappuccino,2.0,3.50,7.00,Cash
17,TX1018,2025-09-16,12:00:03,NaN,NaN,NaN,NaN,NaN
18,TX1019,2025-09-17,12:15:59,Tea,1.0,2.25,2.25,Credit Card
19,TX1020,2025-09-19,12:30:12,Americano,1.0,3.00,3.00,Cash
20,TX1021,2025-09-20,12:45:36,Cappuccino,1.0,3.50,3.50,Credit Card
21,TX1022,2025-09-22,13:00:28,Latte,2.0,4.00,8.00,Mobile Pay
22,TX1023,2025-09-23,13:15:17,Muffin,1.0,2.75,2.75,Cash
23,TX1024,2025-09-24,13:30:54,Brownie,1.0,2.50,2.50,NaN
24,TX1025,2025-09-25,13:45:31,Espresso,NaN,2.75,NaN,Credit Card
25,TX1026,2025-09-26,14:00:09,Latte,1.0,NaN,NaN,Cash

#### Info about DataFrame

In [6]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionID  26 non-null     object
 1   Date           26 non-null     object
 2   Time           26 non-null     object
 3   Item           24 non-null     object
 4   Quantity       22 non-null     float64
 5   PricePerItem   22 non-null     float64
 6   TotalPrice     19 non-null     float64
 7   PaymentMethod  22 non-null     object
dtypes: float64(3), object(5)
memory usage: 1.8+ KB

#### Statistical Info about DataFrame

In [7]:
df_2.describe()

        Quantity  PricePerItem  TotalPrice
count  22.000000     22.000000   19.000000
mean    1.227273      3.170455    3.934211
std     0.428932      0.604479    1.969987
min     1.000000      2.250000    2.250000
25%     1.000000      2.750000    2.750000
50%     1.000000      3.000000    3.000000
75%     1.000000      3.500000    4.000000
max     2.000000      4.250000    8.000000

#### Accessing Data using Rows and Columns df.loc[Rows,Cols[Textual]] and using indexes [df.iloc[Numerical]]

In [8]:
print( 'Row 7 All Columns: \n', df_2.loc[7] )
print( '\n Row 20 Onwards till End All Columns: \n', df_2.loc[20:] )
print( '\n Row 20 Onwards till End Selected Columns: \n', df_2.loc[20:,['Item','PaymentMethod']] )

Row 7 All Columns:
 TransactionID        TX1008
Date             2025-09-05
Time               09:30:42
Item                  Latte
Quantity                1.0
PricePerItem            4.0
TotalPrice              4.0
PaymentMethod    Mobile Pay
Name: 7, dtype: object

 Row 20 Onwards till End All Columns:
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
20        3.50   Credit Card
21        8.00    Mobile Pay
22        2.75          Cash
23        2.50           NaN
24         NaN   Credit Card
25         NaN          Cash

 Row 20 Onwards till End Selected Columns:
           Item PaymentMethod
20  Cappuccino   Credit Card
21       Latte    Mobile Pay
22      Muffin          Cash
23     Brownie           NaN
24    Espresso   Credit Card
25       Latte          Cash

In [9]:
print( 'Row 7 All Columns: \n', df_2.iloc[7] )
print( '\n Row 20 Onwards till End All Columns: \n', df_2.iloc[20:] )
print( '\n Row 20 Onwards till End Selected Columns: \n', df_2.iloc[20:,[0,1,2,3]] )

Row 7 All Columns:
 TransactionID        TX1008
Date             2025-09-05
Time               09:30:42
Item                  Latte
Quantity                1.0
PricePerItem            4.0
TotalPrice              4.0
PaymentMethod    Mobile Pay
Name: 7, dtype: object

 Row 20 Onwards till End All Columns:
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
20        3.50   Credit Card
21        8.00    Mobile Pay
22        2.75          Cash
23        2.50           NaN
24         NaN   Credit Card
25         NaN          Cash

 Row 20 Onwards till End Selected Columns:
    TransactionID        Date      Time        Item
20        TX1021  2025-09-20  12:45:36  Cappuccino
21        TX1022  2025-09-22  13:00:28       Latte
22        TX1023  2025-09-23  13:15:17      Muffin
23        TX1024  2025-09-24  13:30:54     Brownie
24        TX1025  2025-09-25  13:45:31    Espresso
25        TX1026  2025-09-26  14:00:09       Latte

#### Find out Selected Values

In [10]:
print( ' Value at First Row and Third Column : ', df_2.at[0,'Time'] )
print( ' Value at First Row and Third Column : ', df_2.iat[0,2] )

 Value at First Row and Third Column :  08:15:23
 Value at First Row and Third Column :  08:15:23

In [11]:
print( 'First 7 values from Payment Method column : \n ', df_2['PaymentMethod'].head(7) )
print( '\n All Unique values from Payment Method column :', df_2['PaymentMethod'].unique() )

First 7 values from Payment Method column :
  0    Credit Card
1           Cash
2     Mobile Pay
3    Credit Card
4            NaN
5     Mobile Pay
6    Credit Card
Name: PaymentMethod, dtype: object

 All Unique values from Payment Method column : ['Credit Card' 'Cash' 'Mobile Pay' nan]

#### Sort Values in a DataFrame

In [12]:
print( 'DataFrame sorted based on TotalPrice Column Ascending :\n', df_2.sort_values('TotalPrice').head(5) )
print( '\n DataFrame sorted based on TotalPrice Column Descending :\n', df_2.sort_values('TotalPrice',ascending=False).head(5) )

DataFrame sorted based on TotalPrice Column Ascending :
    TransactionID        Date      Time       Item  Quantity  PricePerItem  \
6         TX1007  2025-09-15  09:15:08        Tea       1.0           NaN
18        TX1019  2025-09-17  12:15:59        Tea       1.0          2.25
3         TX1004  2025-09-03  08:50:39  Croissant       1.0          2.50
23        TX1024  2025-09-24  13:30:54    Brownie       1.0          2.50
13        TX1014  2025-09-09  11:00:06      Bagel       1.0          2.75

    TotalPrice PaymentMethod
6         2.25   Credit Card
18        2.25   Credit Card
3         2.50   Credit Card
23        2.50           NaN
13        2.75           NaN

 DataFrame sorted based on TotalPrice Column Descending :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
1         TX1002  2025-09-01  08:22:11       Latte       2.0           4.0
21        TX1022  2025-09-22  13:00:28       Latte       2.0           4.0
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0           3.5
16        TX1017  2025-09-13  11:45:29  Cappuccino       2.0           3.5
7         TX1008  2025-09-05  09:30:42       Latte       1.0           4.0

    TotalPrice PaymentMethod
1          8.0          Cash
21         8.0    Mobile Pay
9          7.0   Credit Card
16         7.0          Cash
7          4.0    Mobile Pay

### Add or Remove Columns

In [13]:
print( 'Before : \n ', df_2[['Item','PricePerItem']].sort_values('PricePerItem').head() )

# Increase the Value of all Price by 20%
df_2['PricePerItem-2'] = df_2['PricePerItem'] + (df_2['PricePerItem'] * 0.2)
print( '\n After : \n ', df_2[['Item','PricePerItem-2']].sort_values('PricePerItem-2').head() )

# Recalculate TotalPrice
df_2['TotalPrice'] = df_2['PricePerItem-2'] * df_2['Quantity']

df_2[['Item','PricePerItem-2','Quantity','TotalPrice']].sort_values('TotalPrice',ascending=False).head()

Before :
           Item  PricePerItem
18        Tea          2.25
3   Croissant          2.50
14  Croissant          2.50
23    Brownie          2.50
13      Bagel          2.75

 After :
           Item  PricePerItem-2
18        Tea             2.7
3   Croissant             3.0
14  Croissant             3.0
23    Brownie             3.0
13      Bagel             3.3

          Item  PricePerItem-2  Quantity  TotalPrice
1        Latte             4.8       2.0         9.6
21       Latte             4.8       2.0         9.6
9   Cappuccino             4.2       2.0         8.4
16  Cappuccino             4.2       2.0         8.4
7        Latte             4.8       1.0         4.8

#### Drop Columns

In [14]:
df_2.drop(columns=['PricePerItem'])

# If we check we don't get any Change cause we didn't actually delete it
print( 'Not Deleteled : ', df_2.head() )

# To delete it use inplace
df_2.drop(columns=['PricePerItem'], inplace=True)
df_2.head()

Not Deleteled :    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
0        TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50
1        TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
2        TX1003  2025-09-12  08:35:46    Espresso       1.0          2.75
3        TX1004  2025-09-03  08:50:39   Croissant       1.0          2.50
4        TX1005  2025-09-07  09:00:02   Americano       1.0          3.00

   TotalPrice PaymentMethod  PricePerItem-2
0         4.2   Credit Card             4.2
1         9.6          Cash             4.8
2         3.3    Mobile Pay             3.3
3         3.0   Credit Card             3.0
4         3.6           NaN             3.6

,TransactionID,Date,Time,Item,Quantity,TotalPrice,PaymentMethod,PricePerItem-2
0,TX1001,2025-09-08,08:15:23,Cappuccino,1.0,4.2,Credit Card,4.2
1,TX1002,2025-09-01,08:22:11,Latte,2.0,9.6,Cash,4.8
2,TX1003,2025-09-12,08:35:46,Espresso,1.0,3.3,Mobile Pay,3.3
3,TX1004,2025-09-03,08:50:39,Croissant,1.0,3.0,Credit Card,3.0
4,TX1005,2025-09-07,09:00:02,Americano,1.0,3.6,NaN,3.6

#### Combine DateTime Columns together

In [15]:
# pd.to_datetime - To Ensure the DateTime DataType for our DateTime instead of it being a String
df_2['DateTime'] = pd.to_datetime((df_2['Date'] + ' ' + df_2['Time']), format='%Y-%m-%d %H:%M:%S')

df_2.drop(columns=['Date','Time'],inplace=True)

df_2.head()

,TransactionID,Item,Quantity,TotalPrice,PaymentMethod,PricePerItem-2,DateTime
0,TX1001,Cappuccino,1.0,4.2,Credit Card,4.2,2025-09-08 08:15:23
1,TX1002,Latte,2.0,9.6,Cash,4.8,2025-09-01 08:22:11
2,TX1003,Espresso,1.0,3.3,Mobile Pay,3.3,2025-09-12 08:35:46
3,TX1004,Croissant,1.0,3.0,Credit Card,3.0,2025-09-03 08:50:39
4,TX1005,Americano,1.0,3.6,NaN,3.6,2025-09-07 09:00:02

#### Rename and Reorder Column

In [16]:
df_2 = df_2.rename(columns={'PricePerItem-2':'PricePerItem'} )
# Or we can do df_2.rename(columns={'PricePerItem-2':'PricePerItem'}, inplace=True )

columnOrder = ['TransactionID', 'DateTime', 'Item', 'PricePerItem', 'Quantity', 'TotalPrice',
       'PaymentMethod']
df_2 = df_2[columnOrder]

df_2.head()

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
4,TX1005,2025-09-07 09:00:02,Americano,3.6,1.0,3.6,NaN

#### Create a Copy of our DataFrame

In [17]:
# If we do Assignment the new var just points to the original dataFrame
df_3 = df_2
print( 'MemLoc #1 : ', id( df_2 ), ' \t MemLoc #2 : ', id( df_3 ) )

# But if we want a separate copy we use copy()
df_copy = df_2.copy()
print( 'MemLoc #3 : ', id( df_2 ), ' \t MemLoc #4 : ', id( df_copy ) )

MemLoc #1 :  2013641688368  	 MemLoc #2 :  2013641688368
MemLoc #3 :  2013641688368  	 MemLoc #4 :  2013641693264

### Handling Null Values

In [18]:
# Non Zero Values have Nulls
print( 'isna() Values :\n', df_2.isna().sum() )

isna() Values :
 TransactionID    0
DateTime         0
Item             2
PricePerItem     4
Quantity         4
TotalPrice       7
PaymentMethod    4
dtype: int64

In [19]:
df_2

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
4,TX1005,2025-09-07 09:00:02,Americano,3.6,1.0,3.6,NaN
5,TX1006,2025-09-02 09:05:55,Mocha,5.1,NaN,NaN,Mobile Pay
6,TX1007,2025-09-15 09:15:08,Tea,NaN,1.0,NaN,Credit Card
7,TX1008,2025-09-05 09:30:42,Latte,4.8,1.0,4.8,Mobile Pay
8,TX1009,2025-09-04 09:45:14,Bagel,3.3,1.0,3.3,Cash
9,TX1010,2025-09-10 10:00:27,Cappuccino,4.2,2.0,8.4,Credit Card
10,TX1011,2025-09-18 10:15:50,Espresso,3.3,1.0,3.3,Cash
11,TX1012,2025-09-21 10:30:19,NaN,3.9,1.0,3.9,Credit Card
12,TX1013,2025-09-06 10:45:34,Mocha,NaN,2.0,NaN,Mobile Pay
13,TX1014,2025-09-09 11:00:06,Bagel,3.3,1.0,3.3,NaN
14,TX1015,2025-09-14 11:15:51,Croissant,3.0,NaN,NaN,Credit Card
15,TX1016,2025-09-11 11:30:45,Latte,4.8,1.0,4.8,Credit Card
16,TX1017,2025-09-13 11:45:29,Cappuccino,4.2,2.0,8.4,Cash
17,TX1018,2025-09-16 12:00:03,NaN,NaN,NaN,NaN,NaN
18,TX1019,2025-09-17 12:15:59,Tea,2.7,1.0,2.7,Credit Card
19,TX1020,2025-09-19 12:30:12,Americano,3.6,1.0,3.6,Cash
20,TX1021,2025-09-20 12:45:36,Cappuccino,4.2,1.0,4.2,Credit Card
21,TX1022,2025-09-22 13:00:28,Latte,4.8,2.0,9.6,Mobile Pay
22,TX1023,2025-09-23 13:15:17,Muffin,3.3,1.0,3.3,Cash
23,TX1024,2025-09-24 13:30:54,Brownie,3.0,1.0,3.0,NaN
24,TX1025,2025-09-25 13:45:31,Espresso,3.3,NaN,NaN,Credit Card
25,TX1026,2025-09-26 14:00:09,Latte,NaN,1.0,NaN,Cash

##### Drop the NAN's from Item and Payment column

In [20]:
df_2.dropna(subset=['Item','PaymentMethod'],inplace=True)

df_2

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
5,TX1006,2025-09-02 09:05:55,Mocha,5.1,NaN,NaN,Mobile Pay
6,TX1007,2025-09-15 09:15:08,Tea,NaN,1.0,NaN,Credit Card
7,TX1008,2025-09-05 09:30:42,Latte,4.8,1.0,4.8,Mobile Pay
8,TX1009,2025-09-04 09:45:14,Bagel,3.3,1.0,3.3,Cash
9,TX1010,2025-09-10 10:00:27,Cappuccino,4.2,2.0,8.4,Credit Card
10,TX1011,2025-09-18 10:15:50,Espresso,3.3,1.0,3.3,Cash
12,TX1013,2025-09-06 10:45:34,Mocha,NaN,2.0,NaN,Mobile Pay
14,TX1015,2025-09-14 11:15:51,Croissant,3.0,NaN,NaN,Credit Card
15,TX1016,2025-09-11 11:30:45,Latte,4.8,1.0,4.8,Credit Card
16,TX1017,2025-09-13 11:45:29,Cappuccino,4.2,2.0,8.4,Cash
18,TX1019,2025-09-17 12:15:59,Tea,2.7,1.0,2.7,Credit Card
19,TX1020,2025-09-19 12:30:12,Americano,3.6,1.0,3.6,Cash
20,TX1021,2025-09-20 12:45:36,Cappuccino,4.2,1.0,4.2,Credit Card
21,TX1022,2025-09-22 13:00:28,Latte,4.8,2.0,9.6,Mobile Pay
22,TX1023,2025-09-23 13:15:17,Muffin,3.3,1.0,3.3,Cash
24,TX1025,2025-09-25 13:45:31,Espresso,3.3,NaN,NaN,Credit Card
25,TX1026,2025-09-26 14:00:09,Latte,NaN,1.0,NaN,Cash

##### Fill in Numeric Columns Item with Price as per ItemType, Quantity with the mode Value and re-calculate TotalPrice

In [21]:
# Fill in PricePerItem with Price as per ItemType
df_2.loc[df_2['Item'] == 'Latte', 'PricePerItem'] = 4.80
df_2.loc[df_2['Item'] == 'Tea', 'PricePerItem'] = 2.70
df_2.loc[df_2['Item'] == 'Mocha', 'PricePerItem'] = 5.10

# Quantity with the mode Value
df_2['Quantity'] = df_2['Quantity'].fillna( df_2['Quantity'].mode()[0] )

# re-calculate TotalPrice
df_2['TotalPrice'] = df_2['Quantity'] * df_2['PricePerItem']
df_2

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
5,TX1006,2025-09-02 09:05:55,Mocha,5.1,1.0,5.1,Mobile Pay
6,TX1007,2025-09-15 09:15:08,Tea,2.7,1.0,2.7,Credit Card
7,TX1008,2025-09-05 09:30:42,Latte,4.8,1.0,4.8,Mobile Pay
8,TX1009,2025-09-04 09:45:14,Bagel,3.3,1.0,3.3,Cash
9,TX1010,2025-09-10 10:00:27,Cappuccino,4.2,2.0,8.4,Credit Card
10,TX1011,2025-09-18 10:15:50,Espresso,3.3,1.0,3.3,Cash
12,TX1013,2025-09-06 10:45:34,Mocha,5.1,2.0,10.2,Mobile Pay
14,TX1015,2025-09-14 11:15:51,Croissant,3.0,1.0,3.0,Credit Card
15,TX1016,2025-09-11 11:30:45,Latte,4.8,1.0,4.8,Credit Card
16,TX1017,2025-09-13 11:45:29,Cappuccino,4.2,2.0,8.4,Cash
18,TX1019,2025-09-17 12:15:59,Tea,2.7,1.0,2.7,Credit Card
19,TX1020,2025-09-19 12:30:12,Americano,3.6,1.0,3.6,Cash
20,TX1021,2025-09-20 12:45:36,Cappuccino,4.2,1.0,4.2,Credit Card
21,TX1022,2025-09-22 13:00:28,Latte,4.8,2.0,9.6,Mobile Pay
22,TX1023,2025-09-23 13:15:17,Muffin,3.3,1.0,3.3,Cash
24,TX1025,2025-09-25 13:45:31,Espresso,3.3,1.0,3.3,Credit Card
25,TX1026,2025-09-26 14:00:09,Latte,4.8,1.0,4.8,Cash

##### Grouby Cost As per ItemType - Highest Sold Items and Max Revenue PaymentMethod

In [22]:
# Get Count GroupBy
print( 'Group By Item Type and Sum of TotalPrice:', df_2.groupby('Item')['TotalPrice'].sum().sort_values(ascending=False) )

print( '\n Group By PaymentMethod and Sum of TotalPrice:', df_2.groupby('PaymentMethod')['TotalPrice'].sum().sort_values(ascending=False) )

Group By Item Type and Sum of TotalPrice: Item
Latte         33.6
Cappuccino    25.2
Mocha         15.3
Espresso       9.9
Croissant      6.0
Tea            5.4
Americano      3.6
Bagel          3.3
Muffin         3.3
Name: TotalPrice, dtype: float64

 Group By PaymentMethod and Sum of TotalPrice: PaymentMethod
Cash           36.3
Credit Card    36.3
Mobile Pay     33.0
Name: TotalPrice, dtype: float64

***