In [1]:
pip install -r requirements.txt

Requirement already satisfied: numpy in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: openpyxl in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 2)) (3.1.5)
Requirement already satisfied: pandas in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 3)) (2.3.3)
Requirement already satisfied: pyarrow in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 4)) (21.0.0)
Requirement already satisfied: pyjanitor in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 5)) (0.31.0)
Requirement already satisfied: ipykernel in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 6)) (6.30.1)
Requirement already satisfied: matplotlib in c:\swares\exploded\python_3_12\lib\site-packages (from -r requirements.txt (line 7)) (3.10.6)
Requirement already satisfied: et-xmlfile in c:\swares\exploded\python_3_12\lib\site-packages (from openpyxl->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\swares\exploded\python_3_12\lib\site-packages (from pandas->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\swares\exploded\python_3_12\lib\site-packages (from pandas->-r requirements.txt (line 3)) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\swares\exploded\python_3_12\lib\site-packages (from pandas->-r requirements.txt (line 3)) (2025.2)
Requirement already satisfied: natsort in c:\swares\exploded\python_3_12\lib\site-packages (from pyjanitor->-r requirements.txt (line 5)) (8.4.0)
Requirement already satisfied: pandas_flavor in c:\swares\exploded\python_3_12\lib\site-packages (from pyjanitor->-r requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: multipledispatch in c:\swares\exploded\python_3_12\lib\site-packages (from pyjanitor->-r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: scipy in c:\swares\exploded\python_3_12\lib\site-packages (from pyjanitor->-r requirements.txt (line 5)) (1.16.2)
Requirement already satisfied: comm>=0.1.1 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (1.8.17)
Requirement already satisfied: ipython>=7.23.1 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (9.6.0)
Requirement already satisfied: jupyter-client>=8.0.0 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (0.1.7)
Requirement already satisfied: nest-asyncio>=1.4 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (24.2)
Requirement already satisfied: psutil>=5.7 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (7.1.0)
Requirement already satisfied: pyzmq>=25 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (27.1.0)
Requirement already satisfied: tornado>=6.2 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (6.5.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\swares\exploded\python_3_12\lib\site-packages (from ipykernel->-r requirements.txt (line 6)) (5.14.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 7)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 7)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 7)) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 7)) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 7)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\swares\exploded\python_3_12\lib\site-packages (from matplotlib->-r requirements.txt (line 7)) (3.2.5)
Requirement already satisfied: colorama in c:\swares\exploded\python_3_12\lib\site-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (0.4.6)
Requirement already satisfied: decorator in c:\swares\exploded\python_3_12\lib\site-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\swares\exploded\python_3_12\lib\site-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\swares\exploded\python_3_12\lib\site-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\swares\exploded\python_3_12\lib\site-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\swares\exploded\python_3_12\lib\site-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (2.19.2)
Requirement already satisfied: stack_data in c:\swares\exploded\python_3_12\lib\site-packages (from ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (0.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\swares\exploded\python_3_12\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->-r requirements.txt (line 6)) (4.3.6)
Requirement already satisfied: pywin32>=300 in c:\swares\exploded\python_3_12\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->-r requirements.txt (line 6)) (311)
Requirement already satisfied: six>=1.5 in c:\swares\exploded\python_3_12\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 3)) (1.17.0)
Requirement already satisfied: xarray in c:\swares\exploded\python_3_12\lib\site-packages (from pandas_flavor->pyjanitor->-r requirements.txt (line 5)) (2025.9.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\swares\exploded\python_3_12\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (0.8.5)
Requirement already satisfied: wcwidth in c:\swares\exploded\python_3_12\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\swares\exploded\python_3_12\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\swares\exploded\python_3_12\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (3.0.0)
Requirement already satisfied: pure-eval in c:\swares\exploded\python_3_12\lib\site-packages (from stack_data->ipython>=7.23.1->ipykernel->-r requirements.txt (line 6)) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Create Sample Dataframe

In [3]:
df_1 = pd.DataFrame( [ [1,2,3], [4,5,6], [7,8,9],[1,2,3], [4,5,6], [7,8,9] ], columns= ['col_1', 'col_2', 'col_3' ], index=['a','b','c','d','e','f'] )
df_1

   col_1  col_2  col_3
a      1      2      3
b      4      5      6
c      7      8      9
d      1      2      3
e      4      5      6
f      7      8      9

In [4]:
print( 'Top 5 : \n', df_1.head() )
print( 'Bottom 5 : \n', df_1.tail() )

Top 5 :
    col_1  col_2  col_3
a      1      2      3
b      4      5      6
c      7      8      9
d      1      2      3
e      4      5      6
Bottom 5 :
    col_1  col_2  col_3
b      4      5      6
c      7      8      9
d      1      2      3
e      4      5      6
f      7      8      9

In [5]:
print( 'Col Names: ', df_1.columns )
print( 'Indexes: ', df_1.index )

Col Names:  Index(['col_1', 'col_2', 'col_3'], dtype='object')
Indexes:  Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

#### Info about DataFrame

In [6]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   6 non-null      int64
 1   col_2   6 non-null      int64
 2   col_3   6 non-null      int64
dtypes: int64(3)
memory usage: 192.0+ bytes

#### Statistical Info about DataFrame

In [7]:
df_1.describe()

          col_1     col_2     col_3
count  6.000000  6.000000  6.000000
mean   4.000000  5.000000  6.000000
std    2.683282  2.683282  2.683282
min    1.000000  2.000000  3.000000
25%    1.750000  2.750000  3.750000
50%    4.000000  5.000000  6.000000
75%    6.250000  7.250000  8.250000
max    7.000000  8.000000  9.000000

##### Unique Values about Dataframe

In [8]:
df_1.nunique()

col_1    3
col_2    3
col_3    3
dtype: int64

##### Size and Shape

In [9]:
print( 'Number of Items:', df_1.size )
print( 'Number of Rows,Cols:', df_1.shape )

Number of Items: 18
Number of Rows,Cols: (6, 3)

***

#### Create Data using ChatGPT - create sample data frame of transactions at a coffee shop in CSV format with at least 25 rows, add a few missing values and NAN's and I want to be able to download the csv file

##### If unable to download create using Python

In [10]:
import pandas as pd
import numpy as np

data = [
    ["TX1001", "2025-09-08", "08:15:23", "Cappuccino", 1, 3.50, 3.50, "Credit Card"],
    ["TX1002", "2025-09-01", "08:22:11", "Latte", 2, 4.00, 8.00, "Cash"],
    ["TX1003", "2025-09-12", "08:35:46", "Espresso", 1, 2.75, 2.75, "Mobile Pay"],
    ["TX1004", "2025-09-03", "08:50:39", "Croissant", 1, 2.50, 2.50, "Credit Card"],
    ["TX1005", "2025-09-07", "09:00:02", "Americano", 1, 3.00, 3.00, None],
    ["TX1006", "2025-09-02", "09:05:55", "Mocha", None, 4.25, None, "Mobile Pay"],
    ["TX1007", "2025-09-15", "09:15:08", "Tea", 1, None, 2.25, "Credit Card"],
    ["TX1008", "2025-09-05", "09:30:42", "Latte", 1, 4.00, 4.00, "Mobile Pay"],
    ["TX1009", "2025-09-04", "09:45:14", "Bagel", 1, 2.75, 2.75, "Cash"],
    ["TX1010", "2025-09-10", "10:00:27", "Cappuccino", 2, 3.50, 7.00, "Credit Card"],
    ["TX1011", "2025-09-18", "10:15:50", "Espresso", 1, 2.75, np.nan, "Cash"],
    ["TX1012", "2025-09-21", "10:30:19", None, 1, 3.25, 3.25, "Credit Card"],
    ["TX1013", "2025-09-06", "10:45:34", "Mocha", 2, np.nan, None, "Mobile Pay"],
    ["TX1014", "2025-09-09", "11:00:06", "Bagel", 1, 2.75, 2.75, None],
    ["TX1015", "2025-09-14", "11:15:51", "Croissant", np.nan, 2.50, np.nan, "Credit Card"],
    ["TX1016", "2025-09-11", "11:30:45", "Latte", 1, 4.00, 4.00, "Credit Card"],
    ["TX1017", "2025-09-13", "11:45:29", "Cappuccino", 2, 3.50, 7.00, "Cash"],
    ["TX1018", "2025-09-16", "12:00:03", None, np.nan, np.nan, np.nan, np.nan],
    ["TX1019", "2025-09-17", "12:15:59", "Tea", 1, 2.25, 2.25, "Credit Card"],
    ["TX1020", "2025-09-19", "12:30:12", "Americano", 1, 3.00, 3.00, "Cash"],
    ["TX1021", "2025-09-20", "12:45:36", "Cappuccino", 1, 3.50, 3.50, "Credit Card"],
    ["TX1022", "2025-09-22", "13:00:28", "Latte", 2, 4.00, 8.00, "Mobile Pay"],
    ["TX1023", "2025-09-23", "13:15:17", "Muffin", 1, 2.75, 2.75, "Cash"],
    ["TX1024", "2025-09-24", "13:30:54", "Brownie", 1, 2.50, 2.50, None],
    ["TX1025", "2025-09-25", "13:45:31", "Espresso", None, 2.75, None, "Credit Card"],
    ["TX1026", "2025-09-26", "14:00:09", "Latte", 1, None, None, "Cash"]
]

columns = ["TransactionID", "Date", "Time", "Item", "Quantity", "PricePerItem", "TotalPrice", "PaymentMethod"]

df = pd.DataFrame(data, columns=columns)

# Save to CSV
df.to_csv("coffee_shop_transactions_with_missing_25_rows.csv", index=False)

In [11]:
df_2 = pd.read_csv( 'coffee_shop_transactions_with_missing_25_rows.csv' )
print( 'Top 10 : \n', df_2.head(10) )
print( 'Bottom 10 : \n', df_2.tail(10) )
print( 'Shape : \n', df_2.shape )

print( '\n Random', df_2.sample(5) )
for i in range(3):
    print( 'Random ',i,' : \n', df_2.sample(5) )

Top 10 :
   TransactionID        Date      Time        Item  Quantity  PricePerItem  \
0        TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50
1        TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
2        TX1003  2025-09-12  08:35:46    Espresso       1.0          2.75
3        TX1004  2025-09-03  08:50:39   Croissant       1.0          2.50
4        TX1005  2025-09-07  09:00:02   Americano       1.0          3.00
5        TX1006  2025-09-02  09:05:55       Mocha       NaN          4.25
6        TX1007  2025-09-15  09:15:08         Tea       1.0           NaN
7        TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
8        TX1009  2025-09-04  09:45:14       Bagel       1.0          2.75
9        TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50

   TotalPrice PaymentMethod
0        3.50   Credit Card
1        8.00          Cash
2        2.75    Mobile Pay
3        2.50   Credit Card
4        3.00           NaN
5         NaN    Mobile Pay
6        2.25   Credit Card
7        4.00    Mobile Pay
8        2.75          Cash
9        7.00   Credit Card
Bottom 10 :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
16        TX1017  2025-09-13  11:45:29  Cappuccino       2.0          3.50
17        TX1018  2025-09-16  12:00:03         NaN       NaN           NaN
18        TX1019  2025-09-17  12:15:59         Tea       1.0          2.25
19        TX1020  2025-09-19  12:30:12   Americano       1.0          3.00
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
16        7.00          Cash
17         NaN           NaN
18        2.25   Credit Card
19        3.00          Cash
20        3.50   Credit Card
21        8.00    Mobile Pay
22        2.75          Cash
23        2.50           NaN
24         NaN   Credit Card
25         NaN          Cash
Shape :
 (26, 8)

 Random    TransactionID        Date      Time    Item  Quantity  PricePerItem  \
5         TX1006  2025-09-02  09:05:55   Mocha       NaN          4.25
8         TX1009  2025-09-04  09:45:14   Bagel       1.0          2.75
18        TX1019  2025-09-17  12:15:59     Tea       1.0          2.25
22        TX1023  2025-09-23  13:15:17  Muffin       1.0          2.75
12        TX1013  2025-09-06  10:45:34   Mocha       2.0           NaN

    TotalPrice PaymentMethod
5          NaN    Mobile Pay
8         2.75          Cash
18        2.25   Credit Card
22        2.75          Cash
12         NaN    Mobile Pay
Random  0  :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
7         TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
14        TX1015  2025-09-14  11:15:51   Croissant       NaN          2.50
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
13        TX1014  2025-09-09  11:00:06       Bagel       1.0          2.75
0         TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50

    TotalPrice PaymentMethod
7         4.00    Mobile Pay
14         NaN   Credit Card
20        3.50   Credit Card
13        2.75           NaN
0         3.50   Credit Card
Random  1  :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
23        TX1024  2025-09-24  13:30:54     Brownie       1.0           2.5
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0           3.5
17        TX1018  2025-09-16  12:00:03         NaN       NaN           NaN
3         TX1004  2025-09-03  08:50:39   Croissant       1.0           2.5
19        TX1020  2025-09-19  12:30:12   Americano       1.0           3.0

    TotalPrice PaymentMethod
23         2.5           NaN
9          7.0   Credit Card
17         NaN           NaN
3          2.5   Credit Card
19         3.0          Cash
Random  2  :
    TransactionID        Date      Time   Item  Quantity  PricePerItem  \
15        TX1016  2025-09-11  11:30:45  Latte       1.0          4.00
21        TX1022  2025-09-22  13:00:28  Latte       2.0          4.00
17        TX1018  2025-09-16  12:00:03    NaN       NaN           NaN
18        TX1019  2025-09-17  12:15:59    Tea       1.0          2.25
25        TX1026  2025-09-26  14:00:09  Latte       1.0           NaN

    TotalPrice PaymentMethod
15        4.00   Credit Card
21        8.00    Mobile Pay
17         NaN           NaN
18        2.25   Credit Card
25         NaN          Cash

In [12]:
df_2

,TransactionID,Date,Time,Item,Quantity,PricePerItem,TotalPrice,PaymentMethod
0,TX1001,2025-09-08,08:15:23,Cappuccino,1.0,3.50,3.50,Credit Card
1,TX1002,2025-09-01,08:22:11,Latte,2.0,4.00,8.00,Cash
2,TX1003,2025-09-12,08:35:46,Espresso,1.0,2.75,2.75,Mobile Pay
3,TX1004,2025-09-03,08:50:39,Croissant,1.0,2.50,2.50,Credit Card
4,TX1005,2025-09-07,09:00:02,Americano,1.0,3.00,3.00,NaN
5,TX1006,2025-09-02,09:05:55,Mocha,NaN,4.25,NaN,Mobile Pay
6,TX1007,2025-09-15,09:15:08,Tea,1.0,NaN,2.25,Credit Card
7,TX1008,2025-09-05,09:30:42,Latte,1.0,4.00,4.00,Mobile Pay
8,TX1009,2025-09-04,09:45:14,Bagel,1.0,2.75,2.75,Cash
9,TX1010,2025-09-10,10:00:27,Cappuccino,2.0,3.50,7.00,Credit Card
10,TX1011,2025-09-18,10:15:50,Espresso,1.0,2.75,NaN,Cash
11,TX1012,2025-09-21,10:30:19,NaN,1.0,3.25,3.25,Credit Card
12,TX1013,2025-09-06,10:45:34,Mocha,2.0,NaN,NaN,Mobile Pay
13,TX1014,2025-09-09,11:00:06,Bagel,1.0,2.75,2.75,NaN
14,TX1015,2025-09-14,11:15:51,Croissant,NaN,2.50,NaN,Credit Card
15,TX1016,2025-09-11,11:30:45,Latte,1.0,4.00,4.00,Credit Card
16,TX1017,2025-09-13,11:45:29,Cappuccino,2.0,3.50,7.00,Cash
17,TX1018,2025-09-16,12:00:03,NaN,NaN,NaN,NaN,NaN
18,TX1019,2025-09-17,12:15:59,Tea,1.0,2.25,2.25,Credit Card
19,TX1020,2025-09-19,12:30:12,Americano,1.0,3.00,3.00,Cash
20,TX1021,2025-09-20,12:45:36,Cappuccino,1.0,3.50,3.50,Credit Card
21,TX1022,2025-09-22,13:00:28,Latte,2.0,4.00,8.00,Mobile Pay
22,TX1023,2025-09-23,13:15:17,Muffin,1.0,2.75,2.75,Cash
23,TX1024,2025-09-24,13:30:54,Brownie,1.0,2.50,2.50,NaN
24,TX1025,2025-09-25,13:45:31,Espresso,NaN,2.75,NaN,Credit Card
25,TX1026,2025-09-26,14:00:09,Latte,1.0,NaN,NaN,Cash

#### Accessing Data using Rows and Columns df.loc[Rows,Cols[Textual]] and using indexes [df.iloc[Numerical]]

In [13]:
print( 'Row 7 All Columns: \n', df_2.loc[7] )
print( '\n Row 1-3 All Columns: \n', df_2.loc[1:3] )
print( '\n Row 1,7,9,11,13 All Columns: \n', df_2.loc[[1,7,9,11,13]] )
print( '\n Row 20 Onwards till End All Columns: \n', df_2.loc[20:] )
print( '\n Row 20 Onwards till End Selected Columns: \n', df_2.loc[20:,['Item','PaymentMethod']] )
print( '\n Row 1,7,9,11,13 Selected Columns: \n', df_2.loc[[1,7,9,11,13],['Time','Item','PaymentMethod']] )

Row 7 All Columns:
 TransactionID        TX1008
Date             2025-09-05
Time               09:30:42
Item                  Latte
Quantity                1.0
PricePerItem            4.0
TotalPrice              4.0
PaymentMethod    Mobile Pay
Name: 7, dtype: object

 Row 1-3 All Columns:
   TransactionID        Date      Time       Item  Quantity  PricePerItem  \
1        TX1002  2025-09-01  08:22:11      Latte       2.0          4.00
2        TX1003  2025-09-12  08:35:46   Espresso       1.0          2.75
3        TX1004  2025-09-03  08:50:39  Croissant       1.0          2.50

   TotalPrice PaymentMethod
1        8.00          Cash
2        2.75    Mobile Pay
3        2.50   Credit Card

 Row 1,7,9,11,13 All Columns:
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
1         TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
7         TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50
11        TX1012  2025-09-21  10:30:19         NaN       1.0          3.25
13        TX1014  2025-09-09  11:00:06       Bagel       1.0          2.75

    TotalPrice PaymentMethod
1         8.00          Cash
7         4.00    Mobile Pay
9         7.00   Credit Card
11        3.25   Credit Card
13        2.75           NaN

 Row 20 Onwards till End All Columns:
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
20        3.50   Credit Card
21        8.00    Mobile Pay
22        2.75          Cash
23        2.50           NaN
24         NaN   Credit Card
25         NaN          Cash

 Row 20 Onwards till End Selected Columns:
           Item PaymentMethod
20  Cappuccino   Credit Card
21       Latte    Mobile Pay
22      Muffin          Cash
23     Brownie           NaN
24    Espresso   Credit Card
25       Latte          Cash

 Row 1,7,9,11,13 Selected Columns:
         Time        Item PaymentMethod
1   08:22:11       Latte          Cash
7   09:30:42       Latte    Mobile Pay
9   10:00:27  Cappuccino   Credit Card
11  10:30:19         NaN   Credit Card
13  11:00:06       Bagel           NaN

In [14]:
print( 'Row 7 All Columns: \n', df_2.iloc[7] )
print( '\n Row 1-3 All Columns: \n', df_2.iloc[1:3] )
print( '\n Row 1,7,9,11,13 All Columns: \n', df_2.iloc[[1,7,9,11,13]] )
print( '\n Row 20 Onwards till End All Columns: \n', df_2.iloc[20:] )
print( '\n Row 20 Onwards till End Selected Columns: \n', df_2.iloc[20:,[0,1,2,3]] )
print( '\n Row 1,7,9,11,13 Selected Columns: \n', df_2.iloc[[1,7,9,11,13],[1,2,3,7]] )

Row 7 All Columns:
 TransactionID        TX1008
Date             2025-09-05
Time               09:30:42
Item                  Latte
Quantity                1.0
PricePerItem            4.0
TotalPrice              4.0
PaymentMethod    Mobile Pay
Name: 7, dtype: object

 Row 1-3 All Columns:
   TransactionID        Date      Time      Item  Quantity  PricePerItem  \
1        TX1002  2025-09-01  08:22:11     Latte       2.0          4.00
2        TX1003  2025-09-12  08:35:46  Espresso       1.0          2.75

   TotalPrice PaymentMethod
1        8.00          Cash
2        2.75    Mobile Pay

 Row 1,7,9,11,13 All Columns:
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
1         TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
7         TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50
11        TX1012  2025-09-21  10:30:19         NaN       1.0          3.25
13        TX1014  2025-09-09  11:00:06       Bagel       1.0          2.75

    TotalPrice PaymentMethod
1         8.00          Cash
7         4.00    Mobile Pay
9         7.00   Credit Card
11        3.25   Credit Card
13        2.75           NaN

 Row 20 Onwards till End All Columns:
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
20        3.50   Credit Card
21        8.00    Mobile Pay
22        2.75          Cash
23        2.50           NaN
24         NaN   Credit Card
25         NaN          Cash

 Row 20 Onwards till End Selected Columns:
    TransactionID        Date      Time        Item
20        TX1021  2025-09-20  12:45:36  Cappuccino
21        TX1022  2025-09-22  13:00:28       Latte
22        TX1023  2025-09-23  13:15:17      Muffin
23        TX1024  2025-09-24  13:30:54     Brownie
24        TX1025  2025-09-25  13:45:31    Espresso
25        TX1026  2025-09-26  14:00:09       Latte

 Row 1,7,9,11,13 Selected Columns:
           Date      Time        Item PaymentMethod
1   2025-09-01  08:22:11       Latte          Cash
7   2025-09-05  09:30:42       Latte    Mobile Pay
9   2025-09-10  10:00:27  Cappuccino   Credit Card
11  2025-09-21  10:30:19         NaN   Credit Card
13  2025-09-09  11:00:06       Bagel           NaN

#### Find out Selected Values

In [15]:
print( ' Value at First Row and Third Column : ', df_2.at[0,'Time'] )
print( ' Value at First Row and Third Column : ', df_2.loc[0,'Time'] )
print( ' Value at First Row and Third Column : ', df_2.iat[0,2] )
print( ' Value at First Row and Third Column : ', df_2.iloc[0,2] )

 Value at First Row and Third Column :  08:15:23
 Value at First Row and Third Column :  08:15:23
 Value at First Row and Third Column :  08:15:23
 Value at First Row and Third Column :  08:15:23

In [16]:
print( 'First 7 values from Payment Method column :', df_2['PaymentMethod'].head(7) )
print( '\n All Unique values from Payment Method column :', df_2['PaymentMethod'].unique() )

First 7 values from Payment Method column : 0    Credit Card
1           Cash
2     Mobile Pay
3    Credit Card
4            NaN
5     Mobile Pay
6    Credit Card
Name: PaymentMethod, dtype: object

 All Unique values from Payment Method column : ['Credit Card' 'Cash' 'Mobile Pay' nan]

#### Sort Values in a DataFrame

In [17]:
print( 'DataFrame sorted based on TotalPrice Column Ascending :\n', df_2.sort_values('TotalPrice') )
print( '\n DataFrame sorted based on TotalPrice Column Descending :\n', df_2.sort_values('TotalPrice',ascending=False) )
print( '\n DataFrame sorted based on TotalPrice Descending and Item Type Ascending :\n', df_2.sort_values(['TotalPrice','Item'],ascending=[False,True]) )

DataFrame sorted based on TotalPrice Column Ascending :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
6         TX1007  2025-09-15  09:15:08         Tea       1.0           NaN
18        TX1019  2025-09-17  12:15:59         Tea       1.0          2.25
3         TX1004  2025-09-03  08:50:39   Croissant       1.0          2.50
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
13        TX1014  2025-09-09  11:00:06       Bagel       1.0          2.75
2         TX1003  2025-09-12  08:35:46    Espresso       1.0          2.75
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
8         TX1009  2025-09-04  09:45:14       Bagel       1.0          2.75
4         TX1005  2025-09-07  09:00:02   Americano       1.0          3.00
19        TX1020  2025-09-19  12:30:12   Americano       1.0          3.00
11        TX1012  2025-09-21  10:30:19         NaN       1.0          3.25
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
0         TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50
7         TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
15        TX1016  2025-09-11  11:30:45       Latte       1.0          4.00
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50
16        TX1017  2025-09-13  11:45:29  Cappuccino       2.0          3.50
1         TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
5         TX1006  2025-09-02  09:05:55       Mocha       NaN          4.25
10        TX1011  2025-09-18  10:15:50    Espresso       1.0          2.75
12        TX1013  2025-09-06  10:45:34       Mocha       2.0           NaN
14        TX1015  2025-09-14  11:15:51   Croissant       NaN          2.50
17        TX1018  2025-09-16  12:00:03         NaN       NaN           NaN
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
6         2.25   Credit Card
18        2.25   Credit Card
3         2.50   Credit Card
23        2.50           NaN
13        2.75           NaN
2         2.75    Mobile Pay
22        2.75          Cash
8         2.75          Cash
4         3.00           NaN
19        3.00          Cash
11        3.25   Credit Card
20        3.50   Credit Card
0         3.50   Credit Card
7         4.00    Mobile Pay
15        4.00   Credit Card
9         7.00   Credit Card
16        7.00          Cash
1         8.00          Cash
21        8.00    Mobile Pay
5          NaN    Mobile Pay
10         NaN          Cash
12         NaN    Mobile Pay
14         NaN   Credit Card
17         NaN           NaN
24         NaN   Credit Card
25         NaN          Cash

 DataFrame sorted based on TotalPrice Column Descending :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
1         TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50
16        TX1017  2025-09-13  11:45:29  Cappuccino       2.0          3.50
7         TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
15        TX1016  2025-09-11  11:30:45       Latte       1.0          4.00
0         TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
11        TX1012  2025-09-21  10:30:19         NaN       1.0          3.25
19        TX1020  2025-09-19  12:30:12   Americano       1.0          3.00
4         TX1005  2025-09-07  09:00:02   Americano       1.0          3.00
2         TX1003  2025-09-12  08:35:46    Espresso       1.0          2.75
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
13        TX1014  2025-09-09  11:00:06       Bagel       1.0          2.75
8         TX1009  2025-09-04  09:45:14       Bagel       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
3         TX1004  2025-09-03  08:50:39   Croissant       1.0          2.50
6         TX1007  2025-09-15  09:15:08         Tea       1.0           NaN
18        TX1019  2025-09-17  12:15:59         Tea       1.0          2.25
5         TX1006  2025-09-02  09:05:55       Mocha       NaN          4.25
10        TX1011  2025-09-18  10:15:50    Espresso       1.0          2.75
12        TX1013  2025-09-06  10:45:34       Mocha       2.0           NaN
14        TX1015  2025-09-14  11:15:51   Croissant       NaN          2.50
17        TX1018  2025-09-16  12:00:03         NaN       NaN           NaN
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod
1         8.00          Cash
21        8.00    Mobile Pay
9         7.00   Credit Card
16        7.00          Cash
7         4.00    Mobile Pay
15        4.00   Credit Card
0         3.50   Credit Card
20        3.50   Credit Card
11        3.25   Credit Card
19        3.00          Cash
4         3.00           NaN
2         2.75    Mobile Pay
22        2.75          Cash
13        2.75           NaN
8         2.75          Cash
23        2.50           NaN
3         2.50   Credit Card
6         2.25   Credit Card
18        2.25   Credit Card
5          NaN    Mobile Pay
10         NaN          Cash
12         NaN    Mobile Pay
14         NaN   Credit Card
17         NaN           NaN
24         NaN   Credit Card
25         NaN          Cash

 DataFrame sorted based on TotalPrice Descending and Item Type Ascending :
    TransactionID        Date      Time        Item  Quantity  PricePerItem  \
1         TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50
16        TX1017  2025-09-13  11:45:29  Cappuccino       2.0          3.50
7         TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
15        TX1016  2025-09-11  11:30:45       Latte       1.0          4.00
0         TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
11        TX1012  2025-09-21  10:30:19         NaN       1.0          3.25
4         TX1005  2025-09-07  09:00:02   Americano       1.0          3.00
19        TX1020  2025-09-19  12:30:12   Americano       1.0          3.00
8         TX1009  2025-09-04  09:45:14       Bagel       1.0          2.75
13        TX1014  2025-09-09  11:00:06       Bagel       1.0          2.75
2         TX1003  2025-09-12  08:35:46    Espresso       1.0          2.75
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
3         TX1004  2025-09-03  08:50:39   Croissant       1.0          2.50
6         TX1007  2025-09-15  09:15:08         Tea       1.0           NaN
18        TX1019  2025-09-17  12:15:59         Tea       1.0          2.25
14        TX1015  2025-09-14  11:15:51   Croissant       NaN          2.50
10        TX1011  2025-09-18  10:15:50    Espresso       1.0          2.75
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN
5         TX1006  2025-09-02  09:05:55       Mocha       NaN          4.25
12        TX1013  2025-09-06  10:45:34       Mocha       2.0           NaN
17        TX1018  2025-09-16  12:00:03         NaN       NaN           NaN

    TotalPrice PaymentMethod
1         8.00          Cash
21        8.00    Mobile Pay
9         7.00   Credit Card
16        7.00          Cash
7         4.00    Mobile Pay
15        4.00   Credit Card
0         3.50   Credit Card
20        3.50   Credit Card
11        3.25   Credit Card
4         3.00           NaN
19        3.00          Cash
8         2.75          Cash
13        2.75           NaN
2         2.75    Mobile Pay
22        2.75          Cash
23        2.50           NaN
3         2.50   Credit Card
6         2.25   Credit Card
18        2.25   Credit Card
14         NaN   Credit Card
10         NaN          Cash
24         NaN   Credit Card
25         NaN          Cash
5          NaN    Mobile Pay
12         NaN    Mobile Pay
17         NaN           NaN

### Add or Remove Columns

In [18]:
print( 'Before : ', df_2[['Item','PricePerItem']].sort_values('PricePerItem') )
# Increase the Value of all Price by 20%
df_2['PricePerItem-2'] = df_2['PricePerItem'] + (df_2['PricePerItem'] * 0.2)
print( '\n After : ', df_2[['Item','PricePerItem-2']].sort_values('PricePerItem-2') )
# Recalculate TotalPrice
df_2['TotalPrice'] = df_2['PricePerItem-2'] * df_2['Quantity']
#print( '\n Calculated : ', df_2[['Item','PricePerItem','Quantity','TotalPrice']].sort_values('TotalPrice',ascending=False) )
df_2[['Item','PricePerItem-2','Quantity','TotalPrice']].sort_values('TotalPrice',ascending=False)

Before :            Item  PricePerItem
18         Tea          2.25
3    Croissant          2.50
14   Croissant          2.50
23     Brownie          2.50
13       Bagel          2.75
10    Espresso          2.75
8        Bagel          2.75
2     Espresso          2.75
22      Muffin          2.75
24    Espresso          2.75
19   Americano          3.00
4    Americano          3.00
11         NaN          3.25
9   Cappuccino          3.50
16  Cappuccino          3.50
0   Cappuccino          3.50
20  Cappuccino          3.50
15       Latte          4.00
7        Latte          4.00
1        Latte          4.00
21       Latte          4.00
5        Mocha          4.25
6          Tea           NaN
12       Mocha           NaN
17         NaN           NaN
25       Latte           NaN

 After :            Item  PricePerItem-2
18         Tea             2.7
3    Croissant             3.0
14   Croissant             3.0
23     Brownie             3.0
13       Bagel             3.3
10    Espresso             3.3
8        Bagel             3.3
2     Espresso             3.3
22      Muffin             3.3
24    Espresso             3.3
19   Americano             3.6
4    Americano             3.6
11         NaN             3.9
9   Cappuccino             4.2
16  Cappuccino             4.2
0   Cappuccino             4.2
20  Cappuccino             4.2
15       Latte             4.8
7        Latte             4.8
1        Latte             4.8
21       Latte             4.8
5        Mocha             5.1
6          Tea             NaN
12       Mocha             NaN
17         NaN             NaN
25       Latte             NaN

          Item  PricePerItem-2  Quantity  TotalPrice
1        Latte             4.8       2.0         9.6
21       Latte             4.8       2.0         9.6
9   Cappuccino             4.2       2.0         8.4
16  Cappuccino             4.2       2.0         8.4
7        Latte             4.8       1.0         4.8
15       Latte             4.8       1.0         4.8
0   Cappuccino             4.2       1.0         4.2
20  Cappuccino             4.2       1.0         4.2
11         NaN             3.9       1.0         3.9
19   Americano             3.6       1.0         3.6
4    Americano             3.6       1.0         3.6
2     Espresso             3.3       1.0         3.3
13       Bagel             3.3       1.0         3.3
8        Bagel             3.3       1.0         3.3
10    Espresso             3.3       1.0         3.3
22      Muffin             3.3       1.0         3.3
3    Croissant             3.0       1.0         3.0
23     Brownie             3.0       1.0         3.0
18         Tea             2.7       1.0         2.7
5        Mocha             5.1       NaN         NaN
6          Tea             NaN       1.0         NaN
12       Mocha             NaN       2.0         NaN
14   Croissant             3.0       NaN         NaN
17         NaN             NaN       NaN         NaN
24    Espresso             3.3       NaN         NaN
25       Latte             NaN       1.0         NaN

#### Drop Columns

In [19]:
df_2.drop(columns=['PricePerItem'])
# If we check we don't get any Change cause we didn't actually delete it
print( 'Not Deleteled : ', df_2 )
# To delete it use inplace
df_2.drop(columns=['PricePerItem'], inplace=True)
df_2

Not Deleteled :     TransactionID        Date      Time        Item  Quantity  PricePerItem  \
0         TX1001  2025-09-08  08:15:23  Cappuccino       1.0          3.50
1         TX1002  2025-09-01  08:22:11       Latte       2.0          4.00
2         TX1003  2025-09-12  08:35:46    Espresso       1.0          2.75
3         TX1004  2025-09-03  08:50:39   Croissant       1.0          2.50
4         TX1005  2025-09-07  09:00:02   Americano       1.0          3.00
5         TX1006  2025-09-02  09:05:55       Mocha       NaN          4.25
6         TX1007  2025-09-15  09:15:08         Tea       1.0           NaN
7         TX1008  2025-09-05  09:30:42       Latte       1.0          4.00
8         TX1009  2025-09-04  09:45:14       Bagel       1.0          2.75
9         TX1010  2025-09-10  10:00:27  Cappuccino       2.0          3.50
10        TX1011  2025-09-18  10:15:50    Espresso       1.0          2.75
11        TX1012  2025-09-21  10:30:19         NaN       1.0          3.25
12        TX1013  2025-09-06  10:45:34       Mocha       2.0           NaN
13        TX1014  2025-09-09  11:00:06       Bagel       1.0          2.75
14        TX1015  2025-09-14  11:15:51   Croissant       NaN          2.50
15        TX1016  2025-09-11  11:30:45       Latte       1.0          4.00
16        TX1017  2025-09-13  11:45:29  Cappuccino       2.0          3.50
17        TX1018  2025-09-16  12:00:03         NaN       NaN           NaN
18        TX1019  2025-09-17  12:15:59         Tea       1.0          2.25
19        TX1020  2025-09-19  12:30:12   Americano       1.0          3.00
20        TX1021  2025-09-20  12:45:36  Cappuccino       1.0          3.50
21        TX1022  2025-09-22  13:00:28       Latte       2.0          4.00
22        TX1023  2025-09-23  13:15:17      Muffin       1.0          2.75
23        TX1024  2025-09-24  13:30:54     Brownie       1.0          2.50
24        TX1025  2025-09-25  13:45:31    Espresso       NaN          2.75
25        TX1026  2025-09-26  14:00:09       Latte       1.0           NaN

    TotalPrice PaymentMethod  PricePerItem-2
0          4.2   Credit Card             4.2
1          9.6          Cash             4.8
2          3.3    Mobile Pay             3.3
3          3.0   Credit Card             3.0
4          3.6           NaN             3.6
5          NaN    Mobile Pay             5.1
6          NaN   Credit Card             NaN
7          4.8    Mobile Pay             4.8
8          3.3          Cash             3.3
9          8.4   Credit Card             4.2
10         3.3          Cash             3.3
11         3.9   Credit Card             3.9
12         NaN    Mobile Pay             NaN
13         3.3           NaN             3.3
14         NaN   Credit Card             3.0
15         4.8   Credit Card             4.8
16         8.4          Cash             4.2
17         NaN           NaN             NaN
18         2.7   Credit Card             2.7
19         3.6          Cash             3.6
20         4.2   Credit Card             4.2
21         9.6    Mobile Pay             4.8
22         3.3          Cash             3.3
23         3.0           NaN             3.0
24         NaN   Credit Card             3.3
25         NaN          Cash             NaN

,TransactionID,Date,Time,Item,Quantity,TotalPrice,PaymentMethod,PricePerItem-2
0,TX1001,2025-09-08,08:15:23,Cappuccino,1.0,4.2,Credit Card,4.2
1,TX1002,2025-09-01,08:22:11,Latte,2.0,9.6,Cash,4.8
2,TX1003,2025-09-12,08:35:46,Espresso,1.0,3.3,Mobile Pay,3.3
3,TX1004,2025-09-03,08:50:39,Croissant,1.0,3.0,Credit Card,3.0
4,TX1005,2025-09-07,09:00:02,Americano,1.0,3.6,NaN,3.6
5,TX1006,2025-09-02,09:05:55,Mocha,NaN,NaN,Mobile Pay,5.1
6,TX1007,2025-09-15,09:15:08,Tea,1.0,NaN,Credit Card,NaN
7,TX1008,2025-09-05,09:30:42,Latte,1.0,4.8,Mobile Pay,4.8
8,TX1009,2025-09-04,09:45:14,Bagel,1.0,3.3,Cash,3.3
9,TX1010,2025-09-10,10:00:27,Cappuccino,2.0,8.4,Credit Card,4.2
10,TX1011,2025-09-18,10:15:50,Espresso,1.0,3.3,Cash,3.3
11,TX1012,2025-09-21,10:30:19,NaN,1.0,3.9,Credit Card,3.9
12,TX1013,2025-09-06,10:45:34,Mocha,2.0,NaN,Mobile Pay,NaN
13,TX1014,2025-09-09,11:00:06,Bagel,1.0,3.3,NaN,3.3
14,TX1015,2025-09-14,11:15:51,Croissant,NaN,NaN,Credit Card,3.0
15,TX1016,2025-09-11,11:30:45,Latte,1.0,4.8,Credit Card,4.8
16,TX1017,2025-09-13,11:45:29,Cappuccino,2.0,8.4,Cash,4.2
17,TX1018,2025-09-16,12:00:03,NaN,NaN,NaN,NaN,NaN
18,TX1019,2025-09-17,12:15:59,Tea,1.0,2.7,Credit Card,2.7
19,TX1020,2025-09-19,12:30:12,Americano,1.0,3.6,Cash,3.6
20,TX1021,2025-09-20,12:45:36,Cappuccino,1.0,4.2,Credit Card,4.2
21,TX1022,2025-09-22,13:00:28,Latte,2.0,9.6,Mobile Pay,4.8
22,TX1023,2025-09-23,13:15:17,Muffin,1.0,3.3,Cash,3.3
23,TX1024,2025-09-24,13:30:54,Brownie,1.0,3.0,NaN,3.0
24,TX1025,2025-09-25,13:45:31,Espresso,NaN,NaN,Credit Card,3.3
25,TX1026,2025-09-26,14:00:09,Latte,1.0,NaN,Cash,NaN

#### Combine DateTime Columns together

In [20]:
# pd.to_datetime - To Ensure the DateTime DataType for our DateTime instead of it being a String
df_2['DateTime'] = pd.to_datetime((df_2['Date'] + ' ' + df_2['Time']), format='%Y-%m-%d %H:%M:%S')
df_2.drop(columns=['Date','Time'],inplace=True)
df_2

,TransactionID,Item,Quantity,TotalPrice,PaymentMethod,PricePerItem-2,DateTime
0,TX1001,Cappuccino,1.0,4.2,Credit Card,4.2,2025-09-08 08:15:23
1,TX1002,Latte,2.0,9.6,Cash,4.8,2025-09-01 08:22:11
2,TX1003,Espresso,1.0,3.3,Mobile Pay,3.3,2025-09-12 08:35:46
3,TX1004,Croissant,1.0,3.0,Credit Card,3.0,2025-09-03 08:50:39
4,TX1005,Americano,1.0,3.6,NaN,3.6,2025-09-07 09:00:02
5,TX1006,Mocha,NaN,NaN,Mobile Pay,5.1,2025-09-02 09:05:55
6,TX1007,Tea,1.0,NaN,Credit Card,NaN,2025-09-15 09:15:08
7,TX1008,Latte,1.0,4.8,Mobile Pay,4.8,2025-09-05 09:30:42
8,TX1009,Bagel,1.0,3.3,Cash,3.3,2025-09-04 09:45:14
9,TX1010,Cappuccino,2.0,8.4,Credit Card,4.2,2025-09-10 10:00:27
10,TX1011,Espresso,1.0,3.3,Cash,3.3,2025-09-18 10:15:50
11,TX1012,NaN,1.0,3.9,Credit Card,3.9,2025-09-21 10:30:19
12,TX1013,Mocha,2.0,NaN,Mobile Pay,NaN,2025-09-06 10:45:34
13,TX1014,Bagel,1.0,3.3,NaN,3.3,2025-09-09 11:00:06
14,TX1015,Croissant,NaN,NaN,Credit Card,3.0,2025-09-14 11:15:51
15,TX1016,Latte,1.0,4.8,Credit Card,4.8,2025-09-11 11:30:45
16,TX1017,Cappuccino,2.0,8.4,Cash,4.2,2025-09-13 11:45:29
17,TX1018,NaN,NaN,NaN,NaN,NaN,2025-09-16 12:00:03
18,TX1019,Tea,1.0,2.7,Credit Card,2.7,2025-09-17 12:15:59
19,TX1020,Americano,1.0,3.6,Cash,3.6,2025-09-19 12:30:12
20,TX1021,Cappuccino,1.0,4.2,Credit Card,4.2,2025-09-20 12:45:36
21,TX1022,Latte,2.0,9.6,Mobile Pay,4.8,2025-09-22 13:00:28
22,TX1023,Muffin,1.0,3.3,Cash,3.3,2025-09-23 13:15:17
23,TX1024,Brownie,1.0,3.0,NaN,3.0,2025-09-24 13:30:54
24,TX1025,Espresso,NaN,NaN,Credit Card,3.3,2025-09-25 13:45:31
25,TX1026,Latte,1.0,NaN,Cash,NaN,2025-09-26 14:00:09

#### Rename and Reorder Column

In [21]:
df_2 = df_2.rename(columns={'PricePerItem-2':'PricePerItem'} )
# Or we can do df_2.rename(columns={'PricePerItem-2':'PricePerItem'}, inplace=True )
columnOrder = ['TransactionID', 'DateTime', 'Item', 'PricePerItem', 'Quantity', 'TotalPrice',
       'PaymentMethod']
df_2 = df_2[columnOrder]
df_2

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
4,TX1005,2025-09-07 09:00:02,Americano,3.6,1.0,3.6,NaN
5,TX1006,2025-09-02 09:05:55,Mocha,5.1,NaN,NaN,Mobile Pay
6,TX1007,2025-09-15 09:15:08,Tea,NaN,1.0,NaN,Credit Card
7,TX1008,2025-09-05 09:30:42,Latte,4.8,1.0,4.8,Mobile Pay
8,TX1009,2025-09-04 09:45:14,Bagel,3.3,1.0,3.3,Cash
9,TX1010,2025-09-10 10:00:27,Cappuccino,4.2,2.0,8.4,Credit Card
10,TX1011,2025-09-18 10:15:50,Espresso,3.3,1.0,3.3,Cash
11,TX1012,2025-09-21 10:30:19,NaN,3.9,1.0,3.9,Credit Card
12,TX1013,2025-09-06 10:45:34,Mocha,NaN,2.0,NaN,Mobile Pay
13,TX1014,2025-09-09 11:00:06,Bagel,3.3,1.0,3.3,NaN
14,TX1015,2025-09-14 11:15:51,Croissant,3.0,NaN,NaN,Credit Card
15,TX1016,2025-09-11 11:30:45,Latte,4.8,1.0,4.8,Credit Card
16,TX1017,2025-09-13 11:45:29,Cappuccino,4.2,2.0,8.4,Cash
17,TX1018,2025-09-16 12:00:03,NaN,NaN,NaN,NaN,NaN
18,TX1019,2025-09-17 12:15:59,Tea,2.7,1.0,2.7,Credit Card
19,TX1020,2025-09-19 12:30:12,Americano,3.6,1.0,3.6,Cash
20,TX1021,2025-09-20 12:45:36,Cappuccino,4.2,1.0,4.2,Credit Card
21,TX1022,2025-09-22 13:00:28,Latte,4.8,2.0,9.6,Mobile Pay
22,TX1023,2025-09-23 13:15:17,Muffin,3.3,1.0,3.3,Cash
23,TX1024,2025-09-24 13:30:54,Brownie,3.0,1.0,3.0,NaN
24,TX1025,2025-09-25 13:45:31,Espresso,3.3,NaN,NaN,Credit Card
25,TX1026,2025-09-26 14:00:09,Latte,NaN,1.0,NaN,Cash

#### Create a Copy of our DataFrame

In [22]:
# If we do Assignment the new var just points to the original dataFrame
df_3 = df_2
print( 'MemLoc #1 : ', id( df_2 ), ' \t MemLoc #2 : ', id( df_3 ) )
# But if we want a separate copy we use copy()
df_copy = df_2.copy()
print( 'MemLoc #3 : ', id( df_2 ), ' \t MemLoc #4 : ', id( df_copy ) )

MemLoc #1 :  1421832740960  	 MemLoc #2 :  1421832740960
MemLoc #3 :  1421832740960  	 MemLoc #4 :  1421832608496

### Handling Null Values

In [23]:
# Non Zero Values have Nulls
print( 'isna() Values :\n', df_2.isna().sum() )
print( '\n notna() Values :\n', df_2.notna().sum() )

isna() Values :
 TransactionID    0
DateTime         0
Item             2
PricePerItem     4
Quantity         4
TotalPrice       7
PaymentMethod    4
dtype: int64

 notna() Values :
 TransactionID    26
DateTime         26
Item             24
PricePerItem     22
Quantity         22
TotalPrice       19
PaymentMethod    22
dtype: int64

In [24]:
df_2

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
4,TX1005,2025-09-07 09:00:02,Americano,3.6,1.0,3.6,NaN
5,TX1006,2025-09-02 09:05:55,Mocha,5.1,NaN,NaN,Mobile Pay
6,TX1007,2025-09-15 09:15:08,Tea,NaN,1.0,NaN,Credit Card
7,TX1008,2025-09-05 09:30:42,Latte,4.8,1.0,4.8,Mobile Pay
8,TX1009,2025-09-04 09:45:14,Bagel,3.3,1.0,3.3,Cash
9,TX1010,2025-09-10 10:00:27,Cappuccino,4.2,2.0,8.4,Credit Card
10,TX1011,2025-09-18 10:15:50,Espresso,3.3,1.0,3.3,Cash
11,TX1012,2025-09-21 10:30:19,NaN,3.9,1.0,3.9,Credit Card
12,TX1013,2025-09-06 10:45:34,Mocha,NaN,2.0,NaN,Mobile Pay
13,TX1014,2025-09-09 11:00:06,Bagel,3.3,1.0,3.3,NaN
14,TX1015,2025-09-14 11:15:51,Croissant,3.0,NaN,NaN,Credit Card
15,TX1016,2025-09-11 11:30:45,Latte,4.8,1.0,4.8,Credit Card
16,TX1017,2025-09-13 11:45:29,Cappuccino,4.2,2.0,8.4,Cash
17,TX1018,2025-09-16 12:00:03,NaN,NaN,NaN,NaN,NaN
18,TX1019,2025-09-17 12:15:59,Tea,2.7,1.0,2.7,Credit Card
19,TX1020,2025-09-19 12:30:12,Americano,3.6,1.0,3.6,Cash
20,TX1021,2025-09-20 12:45:36,Cappuccino,4.2,1.0,4.2,Credit Card
21,TX1022,2025-09-22 13:00:28,Latte,4.8,2.0,9.6,Mobile Pay
22,TX1023,2025-09-23 13:15:17,Muffin,3.3,1.0,3.3,Cash
23,TX1024,2025-09-24 13:30:54,Brownie,3.0,1.0,3.0,NaN
24,TX1025,2025-09-25 13:45:31,Espresso,3.3,NaN,NaN,Credit Card
25,TX1026,2025-09-26 14:00:09,Latte,NaN,1.0,NaN,Cash

##### Drop the NAN's from Item and Payment column

In [25]:
df_2.dropna(subset=['Item','PaymentMethod'],inplace=True)

df_2

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
5,TX1006,2025-09-02 09:05:55,Mocha,5.1,NaN,NaN,Mobile Pay
6,TX1007,2025-09-15 09:15:08,Tea,NaN,1.0,NaN,Credit Card
7,TX1008,2025-09-05 09:30:42,Latte,4.8,1.0,4.8,Mobile Pay
8,TX1009,2025-09-04 09:45:14,Bagel,3.3,1.0,3.3,Cash
9,TX1010,2025-09-10 10:00:27,Cappuccino,4.2,2.0,8.4,Credit Card
10,TX1011,2025-09-18 10:15:50,Espresso,3.3,1.0,3.3,Cash
12,TX1013,2025-09-06 10:45:34,Mocha,NaN,2.0,NaN,Mobile Pay
14,TX1015,2025-09-14 11:15:51,Croissant,3.0,NaN,NaN,Credit Card
15,TX1016,2025-09-11 11:30:45,Latte,4.8,1.0,4.8,Credit Card
16,TX1017,2025-09-13 11:45:29,Cappuccino,4.2,2.0,8.4,Cash
18,TX1019,2025-09-17 12:15:59,Tea,2.7,1.0,2.7,Credit Card
19,TX1020,2025-09-19 12:30:12,Americano,3.6,1.0,3.6,Cash
20,TX1021,2025-09-20 12:45:36,Cappuccino,4.2,1.0,4.2,Credit Card
21,TX1022,2025-09-22 13:00:28,Latte,4.8,2.0,9.6,Mobile Pay
22,TX1023,2025-09-23 13:15:17,Muffin,3.3,1.0,3.3,Cash
24,TX1025,2025-09-25 13:45:31,Espresso,3.3,NaN,NaN,Credit Card
25,TX1026,2025-09-26 14:00:09,Latte,NaN,1.0,NaN,Cash

##### Fill in Numeric Columns Item with Price as per ItemType, Quantity with the mode Value and re-calculate TotalPrice

In [26]:
# Fill in PricePerItem with Price as per ItemType
df_2.loc[df_2['Item'] == 'Latte', 'PricePerItem'] = 4.80
df_2.loc[df_2['Item'] == 'Tea', 'PricePerItem'] = 2.70
df_2.loc[df_2['Item'] == 'Mocha', 'PricePerItem'] = 5.10

# Quantity with the mode Value
df_2['Quantity'] = df_2['Quantity'].fillna( df_2['Quantity'].mode()[0] )

# re-calculate TotalPrice
df_2['TotalPrice'] = df_2['Quantity'] * df_2['PricePerItem']
df_2

,TransactionID,DateTime,Item,PricePerItem,Quantity,TotalPrice,PaymentMethod
0,TX1001,2025-09-08 08:15:23,Cappuccino,4.2,1.0,4.2,Credit Card
1,TX1002,2025-09-01 08:22:11,Latte,4.8,2.0,9.6,Cash
2,TX1003,2025-09-12 08:35:46,Espresso,3.3,1.0,3.3,Mobile Pay
3,TX1004,2025-09-03 08:50:39,Croissant,3.0,1.0,3.0,Credit Card
5,TX1006,2025-09-02 09:05:55,Mocha,5.1,1.0,5.1,Mobile Pay
6,TX1007,2025-09-15 09:15:08,Tea,2.7,1.0,2.7,Credit Card
7,TX1008,2025-09-05 09:30:42,Latte,4.8,1.0,4.8,Mobile Pay
8,TX1009,2025-09-04 09:45:14,Bagel,3.3,1.0,3.3,Cash
9,TX1010,2025-09-10 10:00:27,Cappuccino,4.2,2.0,8.4,Credit Card
10,TX1011,2025-09-18 10:15:50,Espresso,3.3,1.0,3.3,Cash
12,TX1013,2025-09-06 10:45:34,Mocha,5.1,2.0,10.2,Mobile Pay
14,TX1015,2025-09-14 11:15:51,Croissant,3.0,1.0,3.0,Credit Card
15,TX1016,2025-09-11 11:30:45,Latte,4.8,1.0,4.8,Credit Card
16,TX1017,2025-09-13 11:45:29,Cappuccino,4.2,2.0,8.4,Cash
18,TX1019,2025-09-17 12:15:59,Tea,2.7,1.0,2.7,Credit Card
19,TX1020,2025-09-19 12:30:12,Americano,3.6,1.0,3.6,Cash
20,TX1021,2025-09-20 12:45:36,Cappuccino,4.2,1.0,4.2,Credit Card
21,TX1022,2025-09-22 13:00:28,Latte,4.8,2.0,9.6,Mobile Pay
22,TX1023,2025-09-23 13:15:17,Muffin,3.3,1.0,3.3,Cash
24,TX1025,2025-09-25 13:45:31,Espresso,3.3,1.0,3.3,Credit Card
25,TX1026,2025-09-26 14:00:09,Latte,4.8,1.0,4.8,Cash

##### Grouby Cost As per ItemType - Highest Sold Items

In [27]:
# Get Count GroupBy
print( 'Group By Item Type and Sum of TotalPrice:', df_2.groupby('Item')['TotalPrice'].sum().sort_values(ascending=False) )
print( '\n Group By PaymentMethod and Sum of TotalPrice:', df_2.groupby('PaymentMethod')['TotalPrice'].sum().sort_values(ascending=False) )
# print( 'Group By Item Type and Sum of TotalPrice:', df_2.groupby(df_2['DateTime'].dt.time)['TotalPrice'].sum().sort_values(ascending=False) )

Group By Item Type and Sum of TotalPrice: Item
Latte         33.6
Cappuccino    25.2
Mocha         15.3
Espresso       9.9
Croissant      6.0
Tea            5.4
Americano      3.6
Bagel          3.3
Muffin         3.3
Name: TotalPrice, dtype: float64

 Group By PaymentMethod and Sum of TotalPrice: PaymentMethod
Cash           36.3
Credit Card    36.3
Mobile Pay     33.0
Name: TotalPrice, dtype: float64

#### Pivot Table

In [28]:
df_2['Hour'] = df_2['DateTime'].dt.hour
df_2['Minute'] = df_2['DateTime'].dt.minute

pivot_2 = df_2.pivot_table( columns='Item', index='Hour', values='TotalPrice', aggfunc='sum' )

print( 'Sum Normal : \n' , pivot_2.sum() )
print( '\n Sum By Hour : \n' , pivot_2.sum(axis=1).sort_values(ascending=False) )

pivot_2

Sum Normal :
 Item
Americano      3.6
Bagel          3.3
Cappuccino    25.2
Croissant      6.0
Espresso       9.9
Latte         33.6
Mocha         15.3
Muffin         3.3
Tea            5.4
dtype: float64

 Sum By Hour :
 Hour
10    21.9
8     20.1
11    16.2
13    16.2
9     15.9
12    10.5
14     4.8
dtype: float64

Item,Americano,Bagel,Cappuccino,Croissant,Espresso,Latte,Mocha,Muffin,Tea
Hour,,,,,,,,,
8,NaN,NaN,4.2,3.0,3.3,9.6,NaN,NaN,NaN
9,NaN,3.3,NaN,NaN,NaN,4.8,5.1,NaN,2.7
10,NaN,NaN,8.4,NaN,3.3,NaN,10.2,NaN,NaN
11,NaN,NaN,8.4,3.0,NaN,4.8,NaN,NaN,NaN
12,3.6,NaN,4.2,NaN,NaN,NaN,NaN,NaN,2.7
13,NaN,NaN,NaN,NaN,3.3,9.6,NaN,3.3,NaN
14,NaN,NaN,NaN,NaN,NaN,4.8,NaN,NaN,NaN

***

In [29]:
df_bios = pd.read_csv( 'Data/bios.csv' )
df_noc = pd.read_csv( 'Data/noc_regions.csv' )
df_olympicData = pd.read_excel( 'Data/olympics-data.xlsx' )
df_results = pd.read_csv(  'Data/results.csv' )

#### Filtering Data

In [30]:
df_bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [31]:
print( 'Filter based on Height greater than 215 cm All Columns: \n', df_bios.loc[ df_bios['height_cm']  >= 215 ] )
print( '\nFilter based on Height greater than 215 cm Selected Columns: \n', df_bios.loc[ df_bios['height_cm']  >= 215, ['name','NOC','height_cm'] ] )
print( '\nFilter based on Height greater than 215 cm Selected Columns Shorthand way: \n', df_bios[df_bios['height_cm']>=215][['name','NOC','height_cm']] )

Filter based on Height greater than 215 cm All Columns:
         athlete_id                   name   born_date               born_city  \
5089          5108     Viktor Pankrashkin  1957-06-19         Moskva (Moscow)
5583          5606   Paulinho Villas Boas  1963-01-26               São Paulo
5599          5622      Vladimir Andreyev  1945-06-14               Astrakhan
5673          5696         Gunther Behnke  1963-01-19              Leverkusen
5716          5739               Uwe Blab  1962-03-26        München (Munich)
5781          5804         Tommy Burleson  1952-02-24               Crossnore
5796          5819          Andy Campbell  1956-07-21               Melbourne
6223          6250            Lars Hansen  1954-09-27  København (Copenhagen)
6270          6298            Hu Zhangbao  1963-04-05                     NaN
6409          6440       Sergey Kovalenko  1947-08-11                     NaN
6420          6451          Jānis Krūmiņš  1930-01-30                   Cēsis
6504          6537            Luc Longley  1969-01-19               Melbourne
6722          6755       Shaquille O'Neal  1972-03-06                  Newark
6937          6972         David Robinson  1965-08-06                Key West
6978          7013        Arvydas Sabonis  1964-12-19                  Kaunas
7056          7093               Shan Tao  1970-05-30                Tangshan
7074          7111         Paulo da Silva  1963-07-21               São Paulo
7188          7226     Vladimir Tkachenko  1957-09-20               Golovinka
7281          7320       Stojko Vranković  1964-01-22                   Drniš
7298          7337            Wang Zhizhi  1977-07-08                 Beijing
7376          7416    Eurelijus Žukauskas  1973-08-22                Klaipėda
52520        52894           Marcin Nowak  1975-10-17             Częstochowa
52604        52979     Stanislav Dineykin  1973-10-10              Blagodarny
52608        52983        Aleksey Kazakov  1976-03-18      Naberezhnye Chelny
82100        82753          Frédéric Weis  1977-06-22              Thionville
82105        82758           Gregor Fucka  1971-08-07                   Kranj
89070        89782               Yao Ming  1980-09-12          Xuhui District
89075        89787         Roberto Dueñas  1975-11-01                  Madrid
107369      108494              Pau Gasol  1980-07-06               Barcelona
107408      108533       Peter John Ramos  1985-05-23                 Fajardo
112312      113568           Stanko Barać  1986-08-13                  Mostar
112327      113583      Patrick Femerling  1975-03-04                 Hamburg
112330      113586      Ioannis Bourousis  1983-11-17                Karditsa
112332      113588    Andreas Glyniadakis  1981-08-26                  Chania
112337      113593          Hamed Haddadi  1985-05-19                   Ahvaz
112358      113614     Aleksey Savrasenko  1979-02-28               Krasnodar
118663      120400         Timofey Mozgov  1986-07-16                     NaN
118676      120415        Dmitry Musersky  1988-10-29                Makiïvka
120266      122147           Zhang Zhaoxu  1987-11-18                 Binzhou
121694      123709            Salah Mejri  1986-06-15                Jendouba
123850      126093         Tyson Chandler  1982-10-02                 Hanford
130460      133147               Li Muhao  1992-06-02                 Guiyang
130461      133148                Zhou Qi  1996-01-16                Xinxiang
131058      133820            Rudy Gobert  1992-06-26           Saint-Quentin
138671      142084          Ondřej Balvín  1992-09-20          Ústí nad Labem
139365      142836         Moustapha Fall  1992-02-23                   Paris
141018      144554          Yuta Watanabe  1994-10-13         Ayauta district

                            born_region born_country  \
5089                             Moskva          RUS
5583                          São Paulo          BRA
5599                          Astrakhan          RUS
5673                Nordrhein-Westfalen          GER
5716                             Bayern          GER
5781                     North Carolina          USA
5796                           Victoria          AUS
6223                        Hovedstaden          DEN
6270                                NaN          NaN
6409                                NaN          NaN
6420                        Cēsu novads          LAT
6504                           Victoria          AUS
6722                         New Jersey          USA
6937                            Florida          USA
6978                             Kaunas          LTU
7056                              Hebei          CHN
7074                          São Paulo          BRA
7188                     Krasnodar Kray          RUS
7281          Šibensko-kninska županija          CRO
7298                            Beijing          CHN
7376                           Klaipėda          LTU
52520                           Śląskie          POL
52604                    Stavropol Kray          RUS
52608              Respublika Tatarstan          RUS
82100                           Moselle          FRA
82105                             Kranj          SLO
89070                          Shanghai          CHN
89075                            Madrid          ESP
107369                        Barcelona          ESP
107408                      Puerto Rico          PUR
112312  Hercegovačko-neretvanski kanton          BIH
112327                          Hamburg          GER
112330                        Thessalia          GRE
112332                            Kriti          GRE
112337                        Khuzestan          IRI
112358                   Krasnodar Kray          RUS
118663                              NaN          NaN
118676                          Donetsk          UKR
120266                         Shandong          CHN
121694                         Jendouba          TUN
123850                       California          USA
130460                          Guizhou          CHN
130461                            Henan          CHN
131058                            Aisne          FRA
138671                     Ústecký kraj          CZE
139365                            Paris          FRA
141018                           Kagawa          JPN

                               NOC  height_cm  weight_kg   died_date
5089                  Soviet Union      220.0      112.0  1993-07-24
5583                        Brazil      217.0      106.0         NaN
5599                  Soviet Union      215.0       90.0         NaN
5673                       Germany      221.0      114.0         NaN
5716          Germany West Germany      218.0      110.0         NaN
5781                 United States      223.0      102.0         NaN
5796                     Australia      218.0       93.0         NaN
6223                        Canada      216.0      105.0         NaN
6270    People's Republic of China      216.0      135.0         NaN
6409                  Soviet Union      216.0      111.0  2004-11-18
6420                  Soviet Union      218.0      141.0  1994-11-20
6504                     Australia      220.0      135.0         NaN
6722                 United States      216.0      137.0         NaN
6937                 United States      216.0      107.0         NaN
6978        Lithuania Soviet Union      223.0      122.0         NaN
7056    People's Republic of China      215.0      120.0         NaN
7074                        Brazil      217.0      106.0         NaN
7188                  Soviet Union      220.0      110.0         NaN
7281            Croatia Yugoslavia      217.0      115.0         NaN
7298    People's Republic of China      215.0      110.0         NaN
7376                     Lithuania      218.0      115.0         NaN
52520                       Poland      215.0      105.0         NaN
52604           Russian Federation      215.0      101.0         NaN
52608           Russian Federation      217.0      102.0         NaN
82100                       France      218.0      110.0         NaN
82105                        Italy      215.0       98.0         NaN
89070   People's Republic of China      226.0      141.0         NaN
89075                        Spain      221.0      137.0         NaN
107369                       Spain      215.0      115.0         NaN
107408                 Puerto Rico      219.0      113.0         NaN
112312                     Croatia      217.0      110.0         NaN
112327                     Germany      215.0      118.0         NaN
112330                      Greece      215.0      108.0         NaN
112332                      Greece      216.0      115.0         NaN
112337    Islamic Republic of Iran      218.0      110.0         NaN
112358          Russian Federation      215.0      118.0         NaN
118663          Russian Federation      216.0      113.0         NaN
118676          Russian Federation      219.0      104.0         NaN
120266  People's Republic of China      221.0      110.0         NaN
121694                     Tunisia      216.0      110.0         NaN
123850               United States      216.0      107.0         NaN
130460  People's Republic of China      218.0      115.0         NaN
130461  People's Republic of China      217.0       95.0         NaN
131058                      France      215.0      113.0         NaN
138671                     Czechia      216.0      107.0         NaN
139365                      France      218.0        NaN         NaN
141018                       Japan      215.0       97.0         NaN

Filter based on Height greater than 215 cm Selected Columns:
                          name                         NOC  height_cm
5089       Viktor Pankrashkin                Soviet Union      220.0
5583     Paulinho Villas Boas                      Brazil      217.0
5599        Vladimir Andreyev                Soviet Union      215.0
5673           Gunther Behnke                     Germany      221.0
5716                 Uwe Blab        Germany West Germany      218.0
5781           Tommy Burleson               United States      223.0
5796            Andy Campbell                   Australia      218.0
6223              Lars Hansen                      Canada      216.0
6270              Hu Zhangbao  People's Republic of China      216.0
6409         Sergey Kovalenko                Soviet Union      216.0
6420            Jānis Krūmiņš                Soviet Union      218.0
6504              Luc Longley                   Australia      220.0
6722         Shaquille O'Neal               United States      216.0
6937           David Robinson               United States      216.0
6978          Arvydas Sabonis      Lithuania Soviet Union      223.0
7056                 Shan Tao  People's Republic of China      215.0
7074           Paulo da Silva                      Brazil      217.0
7188       Vladimir Tkachenko                Soviet Union      220.0
7281         Stojko Vranković          Croatia Yugoslavia      217.0
7298              Wang Zhizhi  People's Republic of China      215.0
7376      Eurelijus Žukauskas                   Lithuania      218.0
52520            Marcin Nowak                      Poland      215.0
52604      Stanislav Dineykin          Russian Federation      215.0
52608         Aleksey Kazakov          Russian Federation      217.0
82100           Frédéric Weis                      France      218.0
82105            Gregor Fucka                       Italy      215.0
89070                Yao Ming  People's Republic of China      226.0
89075          Roberto Dueñas                       Spain      221.0
107369              Pau Gasol                       Spain      215.0
107408       Peter John Ramos                 Puerto Rico      219.0
112312           Stanko Barać                     Croatia      217.0
112327      Patrick Femerling                     Germany      215.0
112330      Ioannis Bourousis                      Greece      215.0
112332    Andreas Glyniadakis                      Greece      216.0
112337          Hamed Haddadi    Islamic Republic of Iran      218.0
112358     Aleksey Savrasenko          Russian Federation      215.0
118663         Timofey Mozgov          Russian Federation      216.0
118676        Dmitry Musersky          Russian Federation      219.0
120266           Zhang Zhaoxu  People's Republic of China      221.0
121694            Salah Mejri                     Tunisia      216.0
123850         Tyson Chandler               United States      216.0
130460               Li Muhao  People's Republic of China      218.0
130461                Zhou Qi  People's Republic of China      217.0
131058            Rudy Gobert                      France      215.0
138671          Ondřej Balvín                     Czechia      216.0
139365         Moustapha Fall                      France      218.0
141018          Yuta Watanabe                       Japan      215.0

Filter based on Height greater than 215 cm Selected Columns Shorthand way:
                          name                         NOC  height_cm
5089       Viktor Pankrashkin                Soviet Union      220.0
5583     Paulinho Villas Boas                      Brazil      217.0
5599        Vladimir Andreyev                Soviet Union      215.0
5673           Gunther Behnke                     Germany      221.0
5716                 Uwe Blab        Germany West Germany      218.0
5781           Tommy Burleson               United States      223.0
5796            Andy Campbell                   Australia      218.0
6223              Lars Hansen                      Canada      216.0
6270              Hu Zhangbao  People's Republic of China      216.0
6409         Sergey Kovalenko                Soviet Union      216.0
6420            Jānis Krūmiņš                Soviet Union      218.0
6504              Luc Longley                   Australia      220.0
6722         Shaquille O'Neal               United States      216.0
6937           David Robinson               United States      216.0
6978          Arvydas Sabonis      Lithuania Soviet Union      223.0
7056                 Shan Tao  People's Republic of China      215.0
7074           Paulo da Silva                      Brazil      217.0
7188       Vladimir Tkachenko                Soviet Union      220.0
7281         Stojko Vranković          Croatia Yugoslavia      217.0
7298              Wang Zhizhi  People's Republic of China      215.0
7376      Eurelijus Žukauskas                   Lithuania      218.0
52520            Marcin Nowak                      Poland      215.0
52604      Stanislav Dineykin          Russian Federation      215.0
52608         Aleksey Kazakov          Russian Federation      217.0
82100           Frédéric Weis                      France      218.0
82105            Gregor Fucka                       Italy      215.0
89070                Yao Ming  People's Republic of China      226.0
89075          Roberto Dueñas                       Spain      221.0
107369              Pau Gasol                       Spain      215.0
107408       Peter John Ramos                 Puerto Rico      219.0
112312           Stanko Barać                     Croatia      217.0
112327      Patrick Femerling                     Germany      215.0
112330      Ioannis Bourousis                      Greece      215.0
112332    Andreas Glyniadakis                      Greece      216.0
112337          Hamed Haddadi    Islamic Republic of Iran      218.0
112358     Aleksey Savrasenko          Russian Federation      215.0
118663         Timofey Mozgov          Russian Federation      216.0
118676        Dmitry Musersky          Russian Federation      219.0
120266           Zhang Zhaoxu  People's Republic of China      221.0
121694            Salah Mejri                     Tunisia      216.0
123850         Tyson Chandler               United States      216.0
130460               Li Muhao  People's Republic of China      218.0
130461                Zhou Qi  People's Republic of China      217.0
131058            Rudy Gobert                      France      215.0
138671          Ondřej Balvín                     Czechia      216.0
139365         Moustapha Fall                      France      218.0
141018          Yuta Watanabe                       Japan      215.0

##### Filter based on multiple conditions

In [32]:
print( '\nFilter Height >= 215 cm and Weight >= 100KG Selected Columns: \n', 
      df_bios[(df_bios['height_cm']>=215) & (df_bios['weight_kg']>=100) ][['name','NOC','height_cm','weight_kg']] )
print( '\nFilter Height >= 215 cm and Weight >= 100KG and Country like Germany Selected Columns: \n', 
      df_bios[(df_bios['height_cm']>=215) & (df_bios['weight_kg']>=100) & (df_bios['NOC'].str.contains('Germany')) ][['name','NOC','height_cm','weight_kg']] )
print( '\nFilter Height >= 215 cm and Weight >= 100KG and Country like Germany or China [RegExp]: \n', 
      df_bios[(df_bios['height_cm']>=215) & (df_bios['weight_kg']>=100) & (df_bios['NOC'].str.contains('Germany|China')) ][['name','NOC','height_cm','weight_kg']] )
print( '\n Filter Born in USA,FRA,GBR,CAN,IND and name starts with Ron : \n', 
      df_bios[ (df_bios['born_country'].isin(['USA','FRA','GBR','CAN','IND'])) & (df_bios['name'].str.startswith('Ron')) ][['name','born_country','NOC']] )
print( '\n Filter Born in IND and Maharashtra : \n', 
      df_bios.query( "born_country == 'IND'" and "born_region == 'Maharashtra'" ) [['name','born_city','NOC']] )
#      [ (df_bios['born_country'].isin(['USA','FRA','GBR','CAN','IND'])) & (df_bios['name'].str.startswith('Ron')) ][['name','born_country','NOC']] )

Filter Height >= 215 cm and Weight >= 100KG Selected Columns:
                          name                         NOC  height_cm  \
5089       Viktor Pankrashkin                Soviet Union      220.0
5583     Paulinho Villas Boas                      Brazil      217.0
5673           Gunther Behnke                     Germany      221.0
5716                 Uwe Blab        Germany West Germany      218.0
5781           Tommy Burleson               United States      223.0
6223              Lars Hansen                      Canada      216.0
6270              Hu Zhangbao  People's Republic of China      216.0
6409         Sergey Kovalenko                Soviet Union      216.0
6420            Jānis Krūmiņš                Soviet Union      218.0
6504              Luc Longley                   Australia      220.0
6722         Shaquille O'Neal               United States      216.0
6937           David Robinson               United States      216.0
6978          Arvydas Sabonis      Lithuania Soviet Union      223.0
7056                 Shan Tao  People's Republic of China      215.0
7074           Paulo da Silva                      Brazil      217.0
7188       Vladimir Tkachenko                Soviet Union      220.0
7281         Stojko Vranković          Croatia Yugoslavia      217.0
7298              Wang Zhizhi  People's Republic of China      215.0
7376      Eurelijus Žukauskas                   Lithuania      218.0
52520            Marcin Nowak                      Poland      215.0
52604      Stanislav Dineykin          Russian Federation      215.0
52608         Aleksey Kazakov          Russian Federation      217.0
82100           Frédéric Weis                      France      218.0
89070                Yao Ming  People's Republic of China      226.0
89075          Roberto Dueñas                       Spain      221.0
107369              Pau Gasol                       Spain      215.0
107408       Peter John Ramos                 Puerto Rico      219.0
112312           Stanko Barać                     Croatia      217.0
112327      Patrick Femerling                     Germany      215.0
112330      Ioannis Bourousis                      Greece      215.0
112332    Andreas Glyniadakis                      Greece      216.0
112337          Hamed Haddadi    Islamic Republic of Iran      218.0
112358     Aleksey Savrasenko          Russian Federation      215.0
118663         Timofey Mozgov          Russian Federation      216.0
118676        Dmitry Musersky          Russian Federation      219.0
120266           Zhang Zhaoxu  People's Republic of China      221.0
121694            Salah Mejri                     Tunisia      216.0
123850         Tyson Chandler               United States      216.0
130460               Li Muhao  People's Republic of China      218.0
131058            Rudy Gobert                      France      215.0
138671          Ondřej Balvín                     Czechia      216.0

        weight_kg
5089        112.0
5583        106.0
5673        114.0
5716        110.0
5781        102.0
6223        105.0
6270        135.0
6409        111.0
6420        141.0
6504        135.0
6722        137.0
6937        107.0
6978        122.0
7056        120.0
7074        106.0
7188        110.0
7281        115.0
7298        110.0
7376        115.0
52520       105.0
52604       101.0
52608       102.0
82100       110.0
89070       141.0
89075       137.0
107369      115.0
107408      113.0
112312      110.0
112327      118.0
112330      108.0
112332      115.0
112337      110.0
112358      118.0
118663      113.0
118676      104.0
120266      110.0
121694      110.0
123850      107.0
130460      115.0
131058      113.0
138671      107.0

Filter Height >= 215 cm and Weight >= 100KG and Country like Germany Selected Columns:
                      name                   NOC  height_cm  weight_kg
5673       Gunther Behnke               Germany      221.0      114.0
5716             Uwe Blab  Germany West Germany      218.0      110.0
112327  Patrick Femerling               Germany      215.0      118.0

Filter Height >= 215 cm and Weight >= 100KG and Country like Germany or China [RegExp]:
                      name                         NOC  height_cm  weight_kg
5673       Gunther Behnke                     Germany      221.0      114.0
5716             Uwe Blab        Germany West Germany      218.0      110.0
6270          Hu Zhangbao  People's Republic of China      216.0      135.0
7056             Shan Tao  People's Republic of China      215.0      120.0
7298          Wang Zhizhi  People's Republic of China      215.0      110.0
89070            Yao Ming  People's Republic of China      226.0      141.0
112327  Patrick Femerling                     Germany      215.0      118.0
120266       Zhang Zhaoxu  People's Republic of China      221.0      110.0
130460           Li Muhao  People's Republic of China      218.0      115.0

 Filter Born in USA,FRA,GBR,CAN,IND and name starts with Ron :
                        name born_country            NOC
567              Ron Bishop          GBR  Great Britain
3241       Ron Villone, Jr.          USA  United States
3367             Ron Cooper          GBR  Great Britain
3469             Ron Rawson          GBR  Great Britain
3471             Ron Redrup          GBR  Great Britain
...                     ...          ...            ...
105380         Ronda Rousey          USA  United States
122611         Ronny Turiaf          FRA         France
122697         Ronjan Sodhi          IND          India
125416  Ronan Lamy Chappuis          FRA         France
133323           Ronnie Ash          USA  United States

[95 rows x 3 columns]

 Filter Born in IND and Maharashtra :
                             name        born_city            NOC
279              Ali Athar Fyzee           Mumbai          India
285                Kamlesh Mehta           Mumbai          India
12923               Frank Weldon           Mumbai  Great Britain
14593              Bapoo Malcolm           Mumbai          India
18611                John Conroy           Nagpur  Great Britain
18701             Richard Norris           Mumbai  Great Britain
18728            Frederick Scott           Mumbai  Great Britain
19002               Eliza Nelson     Pune (Poona)          India
19012              Richard Allen           Nagpur          India
19018        Ashish Kumar Ballal           Mumbai          India
19039              Lionel Emmett         Achalpur          India
19087                Baboo Nimal           Khadki          India
19096             Dhanraj Pillay           Kirkee          India
22407             Brian Hamilton     Pune (Poona)        Ireland
23226                Rolf Edling           Mumbai         Sweden
33237           Cawas Billimoria           Mumbai          India
41939             Jocelyn Barlow     Pune (Poona)  Great Britain
47050              Peter Squires           Mumbai  Great Britain
47924            Shrichand Bajaj           Mumbai          India
47930              Isaac Mansoor           Mumbai          India
53847               David Sopher           Mumbai          India
56044               Rory Barrett           Mumbai    New Zealand
58269           Ganpat Andhalkar           Punwat          India
58279     Harishchandra Birajdar        Nilangana          India
58290                Maruti Mane      Kavthepiran          India
58308           Dinkkarao Shinde         Kolhapur          India
62023            Harry Jefferson           Mumbai  Great Britain
63392            Farokh Tarapore          Satpati          India
68383               Derek Boosey     Pune (Poona)  Great Britain
68517          Launceston Elliot           Mumbai  Great Britain
69609           Manisha Malhotra           Mumbai          India
70879             Eddie Sequeira           Mumbai          India
72084         Shoichiro Takenaka           Mumbai          Japan
82089               Aparna Popat           Mumbai          India
83644               John Boyagis           Mumbai  Great Britain
90937              Robin D'Abreo           Mumbai         Canada
90978               Jude Menezes           Mumbai          India
92337   Anjali Vedpathak-Bhagwat           Mumbai          India
101677              Pat Sullivan          Lonavla          India
103745         Deepali Deshpande           Mumbai          India
104819           Nikhil Kanetkar     Pune (Poona)          India
107863             Vikram Pillay           Kirkee          India
107864           Viren Rasquinha           Mumbai          India
114280           Virdhawal Khade         Kolhapur          India
118302              Frank Brewin     Pune (Poona)          India
119207             Rahi Sarnobat         Kolhapur          India
119636            Mayookha Johny           Mumbai          India
122966               Jwala Gutta           Wardha          India
128041              Lalita Babar  Satara District          India
128066              Ayonika Paul           Mumbai          India
128068        Prarthana Thombare           Barshi          India
130375            Keegan Pereira           Mumbai         Canada
131622            Anirban Lahiri     Pune (Poona)          India
131627          Devindar Walmiki           Mumbai          India
131632      Dattu Baban Bhokanal           Nashik          India
134610                 Anice Das           Mumbai    Netherlands

#### Categorize folks based on height with .apply() lambda

In [33]:
df_bios['height_category'] = df_bios['height_cm'].apply( lambda x: 'Short' if x < 165 else ( 'Average' if x < 185 else 'Tall') )
df_bios[['name','height_cm','height_category']].head(15)

                       name  height_cm height_category
0     Jean-François Blanchy        NaN            Tall
1            Arnaud Boetsch      183.0         Average
2              Jean Borotra      183.0         Average
3           Jacques Brugnon      168.0         Average
4              Albert Canet        NaN            Tall
5         Nicolas Chatelain      181.0         Average
6             Patrick Chila      180.0         Average
7              Henri Cochet        NaN            Tall
8             Marcel Cousin        NaN            Tall
9        Guy de la Chapelle        NaN            Tall
10  Élie, Comte de Lastours        NaN            Tall
11              Max Decugis        NaN            Tall
12                J. Defert        NaN            Tall
13           Étienne Durand        NaN            Tall
14              Damien Éloi      165.0         Average

#### Merge Data between multiple DataFrames with Merge - Kind of like SQL JOINS
- Convert Born Country Abbreviation to it's fullname

In [34]:
# Inner Join both DataFrames - Choose only values common between the two dataFrames
# pd.merge( df_bios, df_noc, left_on='born_country', right_on='NOC', how='inner' )
print( 'Before 1: ', df_bios['born_country'].isna().sum() )
print( 'Before 2: ', df_bios.shape )
# Ensure Columns in Left DataFrame don't get lost
df_bios_2 = pd.merge( df_bios, df_noc, left_on='born_country', right_on='NOC', how='left' )
print( 'After 1: ', df_bios_2['born_country'].isna().sum() )
print( 'After 2: ', df_bios_2.shape )

Before 1:  34592
Before 2:  (145500, 11)
After 1:  34592
After 2:  (145500, 14)

In [35]:
# 3 new columns get added cause both tables have NOC so NOC_x [df_bios] NOC_y[df_noc], notes[df_noc] and region[df_noc]
df_bios_2

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,AUS,Australia,NaN

#### Let's Rename

In [36]:
df_bios_2.rename(columns={'region':'country_full_name'}, inplace=True) 
df_bios_2

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,NOC_y,country_full_name,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,AUS,Australia,NaN

##### Lets find folks whose born country and Olympic Representation Country is same or different

In [37]:
print( 'Different Country : ', df_bios_2[ df_bios_2['NOC_x'] != df_bios_2['country_full_name'] ].shape )
print( 'Same Country : ', df_bios_2[ df_bios_2['NOC_x'] == df_bios_2['country_full_name'] ].shape )

Different Country :  (73210, 14)
Same Country :  (72290, 14)

#### Combine Multiple DataFrames with concat()

In [38]:
df_India = df_bios_2[ df_bios_2['born_country'] == 'IND'].copy()
df_France = df_bios_2[ df_bios_2['born_country'] == 'FRA'].copy()
df_Canada = df_bios_2[ df_bios_2['born_country'] == 'CAN'].copy()

# India First then Canada and then France
df_INCAFR_combined = pd.concat( [df_India,df_Canada,df_France] )
df_INCAFR_combined

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,NOC_y,country_full_name,notes
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21,Tall,IND,India,NaN
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21,Tall,IND,India,NaN
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01,Tall,IND,India,NaN
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN,Average,IND,India,NaN
274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN,Tall,IND,India,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144652,148348,James Clugnet,1996-12-04,Grenoble,Isère,FRA,Great Britain,NaN,NaN,NaN,Tall,FRA,France,NaN
145009,148720,Margaux Hackett,1999-06-02,Annecy,Haute-Savoie,FRA,New Zealand,NaN,NaN,NaN,Tall,FRA,France,NaN
145281,149002,Elliott Baralo,1998-08-01,Annecy,Haute-Savoie,FRA,Sweden,NaN,NaN,NaN,Tall,FRA,France,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN,Tall,FRA,France,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,FRA,France,NaN

### Aggregating Data

In [39]:
# Get Count GroupBy or for Counts use value_counts()
# df_INCAFR_combined.groupby('born_country')['born_country'].count()
df_INCAFR_combined['born_country'].value_counts()

born_country
FRA    5143
CAN    4616
IND     536
Name: count, dtype: int64

In [40]:
df_INCAFR_combined['born_city'].value_counts()

born_city
Toronto              579
Montréal             468
Vancouver            307
Paris                243
Calgary              197
                    ...
Trouville-sur-Mer      1
Glenboro               1
Méolans-Revel          1
Saint-Priest           1
Budaun                 1
Name: count, Length: 2230, dtype: int64

In [41]:
df_INCAFR_combined[df_INCAFR_combined['born_country'] == 'IND']['born_region'].value_counts()

born_region
Punjab                                 94
Maharashtra                            56
West Bengal                            49
Haryana                                43
Uttar Pradesh                          42
Tamil Nadu                             34
Karnataka                              32
National Capital Territory of Delhi    32
Kerala                                 26
Andhra Pradesh                         23
Madhya Pradesh                         22
Rajasthan                              14
Himachal Pradesh                       10
Manipur                                10
Gujarat                                 9
Bihar                                   6
Assam                                   5
Jharkhand                               5
Jammu and Kashmir                       5
Uttarakhand                             4
Tripura                                 3
Nagaland                                2
Goa                                     2
Chandigarh                              2
Chhattisgarh                            2
Mizoram                                 1
Puducherry                              1
Sikkim                                  1
Orissa                                  1
Name: count, dtype: int64

In [42]:
df_INCAFR_combined.columns

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC_x', 'height_cm', 'weight_kg', 'died_date',
       'height_category', 'NOC_y', 'country_full_name', 'notes'],
      dtype='object')

### .shift(), .rank(), .rolling(), .cumsum()

In [43]:
df_results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

##### Convert Floating Years to Int

In [44]:
df_results['year'].unique()

array([1912., 1920., 1996., 1924., 1992., 2000., 2004., 2008., 1900.,
         nan, 1908., 1896., 1984., 1988., 1904., 2012., 2016., 1976.,
       1972., 1980., 1928., 2020., 1968., 1956., 1952., 1960., 1964.,
       1948., 1932., 1936., 2002., 2006., 2010., 1994., 1998., 2014.,
       2018., 2022.])

In [45]:
year_series = pd.Series(df_results['year'])

df_results['year'] = year_series.astype('Int64')
df_results

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [46]:
df_results['medal'].isna().sum()

np.int64(264269)

In [47]:
df_results.groupby('discipline')['medal'].count().sort_values(ascending=False)

discipline
Athletics                           4256
Swimming (Aquatics)                 3289
Rowing                              3085
Artistic Gymnastics (Gymnastics)    2341
Ice Hockey (Ice Hockey)             1905
                                    ...
Bandy                                  0
Glíma                                  0
Savate                                 0
Speed Skiing (Skiing)                  0
Winter Pentathlon                      0
Name: medal, Length: 93, dtype: int64

***