In [60]:
import pandas as pd
import sqlite3

In [61]:
conn = sqlite3.connect("Product-DB/Product-Orders.db")

df_Products = pd.read_sql_query( 'SELECT * FROM Products', conn )
df_Customers = pd.read_sql_query( 'SELECT * FROM Customers', conn )
df_Orders = pd.read_sql_query( 'SELECT * FROM Orders', conn )

### INNER JOIN - Display Only Common Values - Intersection
- **Inner Join or Join** – This is similar to Intersection of two sets 
- Here, we get just the matching rows from both tables and eliminate others

In [62]:
df_1_inner = pd.read_sql_query( 'SELECT o.orderDateTime, c.customerName, p.productName, p.productPrice, o.orderQuantity, p.productPrice * o.orderQuantity AS totalAmount FROM Customers c INNER JOIN Orders o ON o.customerID = c.customerID INNER JOIN Products p ON o.productID = p.productID', conn )
print( 'Inner Join Shape = ', df_1_inner.shape )
df_1_inner.tail()

Inner Join Shape =  (20, 6)

,orderDateTime,customerName,productName,productPrice,orderQuantity,totalAmount
15,2025-08-02 20:00:00,phoebe.buffay,Apple iPhone,1234.0,2,2468.0
16,2025-08-18 09:45:00,rachel.greene,Samsung Galaxy S24,1099.0,3,3297.0
17,2025-09-01 08:20:00,gunther,Sony WH-1000XM5,499.0,5,2495.0
18,2025-09-14 12:40:00,janice,Amazon Echo,149.0,7,1043.0
19,2025-09-28 22:15:00,ms.chanandler bong,iPad Pro,1299.0,1,1299.0

### RIGHT JOIN - All Values from Right Table and only Matching Values from the Left Table
- **Right Join or Right Outer Join** – This is similar to Set Difference.
- Here we get the matching rows in addition to the non-matching rows from the Right table.
- Get the matching rows + non-matching rows from the Right table

In [63]:
df_1_right = pd.read_sql_query( 'SELECT o.orderDateTime, c.customerName, p.productName, p.productPrice, o.orderQuantity, p.productPrice * o.orderQuantity AS totalAmount FROM Customers c RIGHT JOIN Orders o ON o.customerID = c.customerID RIGHT JOIN Products p ON o.productID = p.productID', conn )
print( 'Right Join Shape = ', df_1_right.shape )
df_1_right.tail()

Right Join Shape =  (20, 6)

,orderDateTime,customerName,productName,productPrice,orderQuantity,totalAmount
15,2025-09-14 12:40:00,janice,Amazon Echo,149.0,7,1043.0
16,2025-04-22 17:25:00,ms.chanandler bong,Sony WH-1000XM5,499.0,8,3992.0
17,2025-09-28 22:15:00,ms.chanandler bong,iPad Pro,1299.0,1,1299.0
18,2025-05-01 12:05:00,ken addams,Amazon Echo,149.0,12,1788.0
19,2025-05-15 15:15:00,princess consuela bananahammock,iPad Pro,1299.0,6,7794.0

### LEFT JOIN - All Values from Left Table and only Matching Values from the Right Table
- **Left Join or Left Outer Join** – This is similar to Set Difference. 
- Here we will get the matching rows in addition to the non-matching rows from the Left table
- Get the matching rows + non-matching rows from the Left table

In [64]:
df_1_left = pd.read_sql_query( 'SELECT o.orderDateTime, c.customerName, p.productName, p.productPrice, o.orderQuantity, p.productPrice * o.orderQuantity AS totalAmount FROM Customers c LEFT JOIN Orders o ON o.customerID = c.customerID LEFT JOIN Products p ON o.productID = p.productID', conn )
print( 'Left Join Shape = ', df_1_left.shape )
df_1_left.tail(10)

Left Join Shape =  (26, 6)

,orderDateTime,customerName,productName,productPrice,orderQuantity,totalAmount
16,2025-09-28 22:15:00,ms.chanandler bong,iPad Pro,1299.0,1.0,1299.0
17,2025-04-22 17:25:00,ms.chanandler bong,Sony WH-1000XM5,499.0,8.0,3992.0
18,2025-05-01 12:05:00,ken addams,Amazon Echo,149.0,12.0,1788.0
19,2025-05-15 15:15:00,princess consuela bananahammock,iPad Pro,1299.0,6.0,7794.0
20,None,mike.hannigan,None,NaN,NaN,NaN
21,None,ben.geller,None,NaN,NaN,NaN
22,None,emma.geller,None,NaN,NaN,NaN
23,None,frank.buffay.jr.jr,None,NaN,NaN,NaN
24,None,leslie.buffay,None,NaN,NaN,NaN
25,None,chandler.buffay,None,NaN,NaN,NaN

### Cross Join – Here we get the cartesian product
- **Cartesian Product = number of rows of table1 * number of rows of table2**
- Since Cross Joins give us the Cartesian Product, we don’t need to specify a condition

In [65]:
df_1_cross = pd.read_sql_query( 'SELECT c.customerName, p.productName FROM Customers c CROSS JOIN Products p', conn )
print( 'Products Shape = ', df_Products.shape )
print( 'Customers Shape = ', df_Customers.shape )
print( 'Cross Join Shape = ', df_1_cross.shape )
print( '\n Cross Join Head = \n', df_1_cross.head() )
print( '\n Cross Join Tail = \n', df_1_cross.tail() )

Products Shape =  (15, 4)
Customers Shape =  (17, 4)
Cross Join Shape =  (255, 2)

 Cross Join Head =
     customerName         productName
0  chandler.bing        Apple iPhone
1  chandler.bing          HP Spectre
2  chandler.bing        Garmin Watch
3  chandler.bing           Nespresso
4  chandler.bing  Samsung Galaxy S24

 Cross Join Tail =
         customerName         productName
250  chandler.buffay            iPad Pro
251  chandler.buffay  Lenovo ThinkPad X1
252  chandler.buffay       GoPro Hero 12
253  chandler.buffay       Canon EOS R10
254  chandler.buffay     Fitbit Charge 6

***

### Merge DataFrames using Left, Right Outer and Inner : .merge()
- **Similar to SQL JOINS**
- Merge DataFrame1 and DataFrame2 and Pass as an Argument with DataFrame3

#### Inner Join

In [66]:
df_2_inner = pd.merge( 
    pd.merge(df_Customers, df_Orders, on='customerID', how='inner'),
    df_Products,
    on='productID', how='inner')
print( 'Inner Join Shape = ', df_2_inner.shape )
df_2_inner.tail()

Inner Join Shape =  (20, 11)

,customerID,customerName,customerEmail,customerCity,orderID,orderQuantity,orderDateTime,productID,productName,productType,productPrice
15,8,janice,janice@ohmygod.com,New York,19,7,2025-09-14 12:40:00,10,Amazon Echo,Smart Speaker,149.0
16,9,ms.chanandler bong,ms.chanandler.bong@friends.com,New York,9,8,2025-04-22 17:25:00,9,Sony WH-1000XM5,Headphones,499.0
17,9,ms.chanandler bong,ms.chanandler.bong@friends.com,New York,20,1,2025-09-28 22:15:00,11,iPad Pro,Tablet,1299.0
18,10,ken addams,ken.addams@friends.com,New York,10,12,2025-05-01 12:05:00,10,Amazon Echo,Smart Speaker,149.0
19,11,princess consuela bananahammock,princess.bananahammock@friends.com,New York,11,6,2025-05-15 15:15:00,11,iPad Pro,Tablet,1299.0

### Outer Join:
- Return Matched and Unmatched Values from either or both the Tables

In [67]:
df_2_outer = pd.merge( 
    pd.merge(df_Customers, df_Orders, on='customerID', how='outer'),
    df_Products,
    on='productID', how='outer')
print( 'Outer Join Shape = ', df_2_outer.shape )
df_2_outer.tail(10)

Outer Join Shape =  (26, 11)

,customerID,customerName,customerEmail,customerCity,orderID,orderQuantity,orderDateTime,productID,productName,productType,productPrice
16,1,chandler.bing,chandler.bing@friends.com,New York,12.0,3.0,2025-06-01 09:50:00,12.0,Lenovo ThinkPad X1,Laptop,1999.0
17,2,monica.geller,monica.geller@friends.com,New York,13.0,9.0,2025-06-12 11:10:00,13.0,GoPro Hero 12,Camera,449.0
18,3,ross.geller,ross.geller@friends.com,New York,14.0,1.0,2025-07-03 10:00:00,14.0,Canon EOS R10,Camera,1399.0
19,4,joey.tribbiani,joey.tribbiani@friends.com,New York,15.0,11.0,2025-07-20 18:25:00,15.0,Fitbit Charge 6,Smartwatch,179.0
20,12,mike.hannigan,mike.hannigan@friends.com,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,13,ben.geller,ben.geller@friends.com,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,14,emma.geller,emma.geller@friends.com,New Jersey,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,15,frank.buffay.jr.jr,frank.buffay.jr.jr@friends.com,Long Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,16,leslie.buffay,leslie.buffay@friends.com,Long Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,17,chandler.buffay,chandler.buffay@friends.com,Long Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Left Join

In [68]:
df_2_left = pd.merge( 
    pd.merge(df_Customers, df_Orders, on='customerID', how='left'),
    df_Products,
    on='productID', how='left')
print( 'Left Join Shape = ', df_2_left.shape )
df_2_left.tail(10)

Left Join Shape =  (26, 11)

,customerID,customerName,customerEmail,customerCity,orderID,orderQuantity,orderDateTime,productID,productName,productType,productPrice
16,9,ms.chanandler bong,ms.chanandler.bong@friends.com,New York,9.0,8.0,2025-04-22 17:25:00,9.0,Sony WH-1000XM5,Headphones,499.0
17,9,ms.chanandler bong,ms.chanandler.bong@friends.com,New York,20.0,1.0,2025-09-28 22:15:00,11.0,iPad Pro,Tablet,1299.0
18,10,ken addams,ken.addams@friends.com,New York,10.0,12.0,2025-05-01 12:05:00,10.0,Amazon Echo,Smart Speaker,149.0
19,11,princess consuela bananahammock,princess.bananahammock@friends.com,New York,11.0,6.0,2025-05-15 15:15:00,11.0,iPad Pro,Tablet,1299.0
20,12,mike.hannigan,mike.hannigan@friends.com,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,13,ben.geller,ben.geller@friends.com,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,14,emma.geller,emma.geller@friends.com,New Jersey,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,15,frank.buffay.jr.jr,frank.buffay.jr.jr@friends.com,Long Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,16,leslie.buffay,leslie.buffay@friends.com,Long Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,17,chandler.buffay,chandler.buffay@friends.com,Long Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Right Join

In [69]:
df_2_right = pd.merge( 
    pd.merge(df_Customers, df_Orders, on='customerID', how='right'),
    df_Products,
    on='productID', how='right')
print( 'Right Join Shape = ', df_2_right.shape )
df_2_right.tail()

Right Join Shape =  (20, 11)

,customerID,customerName,customerEmail,customerCity,orderID,orderQuantity,orderDateTime,productID,productName,productType,productPrice
15,9,ms.chanandler bong,ms.chanandler.bong@friends.com,New York,20,1,2025-09-28 22:15:00,11,iPad Pro,Tablet,1299.0
16,1,chandler.bing,chandler.bing@friends.com,New York,12,3,2025-06-01 09:50:00,12,Lenovo ThinkPad X1,Laptop,1999.0
17,2,monica.geller,monica.geller@friends.com,New York,13,9,2025-06-12 11:10:00,13,GoPro Hero 12,Camera,449.0
18,3,ross.geller,ross.geller@friends.com,New York,14,1,2025-07-03 10:00:00,14,Canon EOS R10,Camera,1399.0
19,4,joey.tribbiani,joey.tribbiani@friends.com,New York,15,11,2025-07-20 18:25:00,15,Fitbit Charge 6,Smartwatch,179.0

***

### Concatenate DataFrames using Left, Right Outer and Inner : .concat()
- **Add Rows** *(one below the Other)* or **Columns** *(Side by Side)* and Add **NaN for missing** items
- Specify **join** type
- Also Specify the **Axis**, **axis=0** means **concatenate** along the **rows** and **axis=1** means **concatenate** along the **columns**
- **ignore_index=True**: This resets the index after concatenation, creating a new default integer index rather than retaining the original indices.

#### Inner Concat

In [70]:
df_3_inner = pd.concat( [df_Customers, df_Orders, df_Products], axis=1, join='inner', ignore_index=True )
print( 'Inner Concat Shape = ', df_3_inner.shape )
df_3_inner.tail()

Inner Concat Shape =  (15, 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
10,11,princess consuela bananahammock,princess.bananahammock@friends.com,New York,11,6,2025-05-15 15:15:00,11,11,11,iPad Pro,Tablet,1299.0
11,12,mike.hannigan,mike.hannigan@friends.com,New York,12,3,2025-06-01 09:50:00,12,1,12,Lenovo ThinkPad X1,Laptop,1999.0
12,13,ben.geller,ben.geller@friends.com,New York,13,9,2025-06-12 11:10:00,13,2,13,GoPro Hero 12,Camera,449.0
13,14,emma.geller,emma.geller@friends.com,New Jersey,14,1,2025-07-03 10:00:00,14,3,14,Canon EOS R10,Camera,1399.0
14,15,frank.buffay.jr.jr,frank.buffay.jr.jr@friends.com,Long Island,15,11,2025-07-20 18:25:00,15,4,15,Fitbit Charge 6,Smartwatch,179.0

#### Outer Concat

In [71]:
df_3_outer = pd.concat( [df_Customers, df_Orders, df_Products], axis=1, join='outer', ignore_index=True )
print( 'Outer Concat Shape = ', df_3_outer.shape )
df_3_outer.tail()

Outer Concat Shape =  (20, 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
15,16.0,leslie.buffay,leslie.buffay@friends.com,Long Island,16,2,2025-08-02 20:00:00,1,5,NaN,NaN,NaN,NaN
16,17.0,chandler.buffay,chandler.buffay@friends.com,Long Island,17,3,2025-08-18 09:45:00,5,6,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,18,5,2025-09-01 08:20:00,9,7,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,19,7,2025-09-14 12:40:00,10,8,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,20,1,2025-09-28 22:15:00,11,9,NaN,NaN,NaN,NaN

### Right or Left Concat Not Allowed : ValueError: Only can inner (intersect) or outer (union) join the other axis

In [72]:
# df_3_left = pd.concat( [df_Customers, df_Orders, df_Products], axis=0, join='left', ignore_index=True )
# df_3_right = pd.concat( [df_Customers, df_Orders, df_Products], axis=0, join='right', ignore_index=True )

***

### join() is used to combine DataFrames based on their indices.
- **join() merges two or more tables horizontally (side by side)**
- **Both DataFrames must have the same or compatible indices.**

In [81]:
# Customers DataFrame
df_cust = pd.DataFrame({
    'Name': ['Chandler', 'Monica', 'Ross'],
    'City': ['New York', 'Seattle', 'Long Island']
}, index=[1, 2, 3])

df_cust

       Name         City
1  Chandler     New York
2    Monica      Seattle
3      Ross  Long Island

In [82]:
# Orders DataFrame
df_ord = pd.DataFrame({
    'OrderID': [101, 102, 103],
    'ProductID': [11, 12, 13],
    'Quantity': [2, 1, 4]
}, index=[1, 2, 3])
df_ord

   OrderID  ProductID  Quantity
1      101         11         2
2      102         12         1
3      103         13         4

In [80]:
# Products DataFrame
df_prod = pd.DataFrame({
    'ProductName': ['iPhone', 'Laptop', 'Smartwatch'],
    'Price': [999, 1899, 299]
}, index=[11, 12, 13])
df_prod

   ProductName  Price
11      iPhone    999
12      Laptop   1899
13  Smartwatch    299

#### Same Indices for both the DataFrames

In [83]:
df_cust_ord = df_cust.join( df_ord )
df_cust_ord

       Name         City  OrderID  ProductID  Quantity
1  Chandler     New York      101         11         2
2    Monica      Seattle      102         12         1
3      Ross  Long Island      103         13         4

#### Join products using ProductID as a key (need to reset index alignment)

In [84]:
df_join = df_cust_ord.join( df_prod, on='ProductID' )
df_join

       Name         City  OrderID  ProductID  Quantity ProductName  Price
1  Chandler     New York      101         11         2      iPhone    999
2    Monica      Seattle      102         12         1      Laptop   1899
3      Ross  Long Island      103         13         4  Smartwatch    299

### join() merges side by side based on index by default.

#### When joining with Products, we use on=*'ProductID'* since its index *(11,12,13)* matches the values in the *ProductID* column of Order DataFrame.

***